const { app, BrowserWindow, ipcMain, session } = require('electron');
const path = require('path');
const { pathToFileURL } = require('url');
const { execFile } = require('child_process');
const { loadState, saveState, backup, close } = require('./database.cjs');

let win;
const isDev = !app.isPackaged;
const DEV_URL = 'http://127.0.0.1:5173/';
const LOCAL_SCHEME = 'file:';
function psJson(script){return new Promise(resolve=>execFile('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout:15000},(err,stdout)=>{if(err)return resolve([]);try{resolve(JSON.parse(stdout||'[]'))}catch{resolve([])}}))}
function psRun(script,timeout=15000){return new Promise(resolve=>execFile('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout},(err,stdout,stderr)=>resolve({ok:!err,error:err?.message||String(stderr||'')||null,stdout:String(stdout||'')})))}
function installSecurityHeaders(){session.defaultSession.webRequest.onHeadersReceived((details,callback)=>{const headers={...details.responseHeaders};headers['Content-Security-Policy']=[isDev?"default-src 'self' http://127.0.0.1:5173; connect-src 'self' http://127.0.0.1:5173 ws://127.0.0.1:5173; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval'":"default-src 'self'; connect-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'"];headers['X-Content-Type-Options']=['nosniff'];headers['X-Frame-Options']=['DENY'];callback({responseHeaders:headers})})}
async function listWindowsPrinters(){if(process.platform!=='win32')return[];const ps=`$items=@();try{$items+=@(Get-CimInstance Win32_SerialPort|%{[pscustomobject]@{id=$_.DeviceID;name=$_.Name;description=$_.Description;port=$_.DeviceID;transportPort=$_.DeviceID;type='COM / Bluetooth SPP';pnpId=$_.PNPDeviceID}})}catch{};try{$items+=@(Get-Printer|%{[pscustomobject]@{id=$_.Name;name=$_.Name;description=$_.DriverName;port=$_.PortName;transportPort=if($_.PortName -match '^COM\\d+$'){$_.PortName}else{''};type='Windows Printer';printerName=$_.Name}})}catch{};$items|ConvertTo-Json -Compress;`;const data=await psJson(ps);const rows=Array.isArray(data)?data:(data&&(data.id||data.name)?[data]:[]);const seen=new Set();return rows.filter(x=>{const k=`${x.id}|${x.port}|${x.type}`;if(seen.has(k))return false;seen.add(k);return true})}
async function loadDevUrl(){for(let n=0;n<30;n++){if(!win||win.isDestroyed())return;try{await win.loadURL(DEV_URL);return}catch(err){if(n===29)console.error('[MK POS] loadURL failed',err.message);await new Promise(r=>setTimeout(r,500))}}}
function isAllowedNavigation(url){if(isDev&&url.startsWith(DEV_URL))return true;try{return new URL(url).protocol===LOCAL_SCHEME}catch{return false}}
function createWindow(){win=new BrowserWindow({width:1440,height:900,minWidth:1024,minHeight:680,show:true,backgroundColor:'#f6f7fb',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,webSecurity:true,allowRunningInsecureContent:false,devTools:isDev}});win.webContents.on('will-navigate',(event,url)=>{if(!isAllowedNavigation(url))event.preventDefault()});win.webContents.setWindowOpenHandler(({url})=>isAllowedNavigation(url)?{action:'allow'}:{action:'deny'});win.webContents.on('did-fail-load',(_e,errorCode,errorDescription,validatedURL)=>console.error('[MK POS] did-fail-load',errorCode,errorDescription,validatedURL));win.webContents.on('render-process-gone',(_e,details)=>console.error('[MK POS] render-process-gone',details));win.webContents.on('console-message',(_e,level,message,line,source)=>{if(level>=2)console.error('[MK POS renderer]',message,source+':'+line)});if(isDev)loadDevUrl();else win.loadURL(pathToFileURL(path.join(__dirname,'..','dist','index.html')).href).catch(err=>console.error('[MK POS] packaged load failed',err.message))}

ipcMain.on('db:load-state-sync',(event)=>{try{event.returnValue=loadState()}catch(error){console.error('[MK POS] database load failed',error);event.returnValue=null}});
ipcMain.on('db:save-state-sync',(event,{state,actor}={})=>{try{event.returnValue=saveState(state,actor)}catch(error){console.error('[MK POS] database save failed',error);event.returnValue={ok:false,error:'Database write failed'}}});
ipcMain.handle('db:backup',(_event,{targetPath}={})=>{if(typeof targetPath!=='string'||!targetPath.trim())throw new Error('Invalid backup path');return backup(targetPath)});

app.whenReady().then(()=>{installSecurityHeaders();createWindow();app.on('activate',()=>{if(!BrowserWindow.getAllWindows().length)createWindow()})});
function safePort(v){const p=String(v||'').trim().toUpperCase();return /^COM\d+$/.test(p)?p:null}
async function getComPorts(){if(process.platform!=='win32')return[];const data=await psJson(`@(Get-CimInstance Win32_SerialPort|%{$_.DeviceID})|ConvertTo-Json -Compress`);const rows=Array.isArray(data)?data:(data?[data]:[]);return rows.map(s=>safePort(s)).filter(Boolean)}
function bytesFrom(data){if(Array.isArray(data))return Buffer.from(data.map(Number).filter(Number.isFinite).map(n=>Math.max(0,Math.min(255,n))));if(Buffer.isBuffer(data))return data;return Buffer.from(String(data||''),'binary')}
async function serialSend(port,data,baudRate=9600,signals={dtr:false,rts:false}){const p=safePort(port);if(!p)return{ok:false,transport:'bluetooth-spp',error:'Invalid COM port'};const bytes=bytesFrom(data);const b=bytes.toString('base64');const safe=p.replace(/'/g,"''");const rate=Math.max(300,Math.min(4000000,Number(baudRate)||9600));const dtr=!!signals.dtr;const rts=!!signals.rts;const script=`$ErrorActionPreference='Stop';$b=[Convert]::FromBase64String('${b}');$p=New-Object System.IO.Ports.SerialPort '${safe}',${rate},None,8,one;$p.Handshake=[System.IO.Ports.Handshake]::None;$p.DtrEnable=${dtr?'$true':'$false'};$p.RtsEnable=${rts?'$true':'$false'};$p.WriteTimeout=2500;$p.ReadTimeout=500;$p.Open();try{$p.Write($b,0,$b.Length);$p.BaseStream.Flush()}finally{if($p.IsOpen){$p.Close();$p.Dispose()}};Write-Output ('SENT='+$b.Length)`;const r=await psRun(script,5000);return{...r,transport:'bluetooth-spp',bytes:bytes.length,port:p,baudRate:rate,dtr,rts}}
async function queueSend(printerName,data){if(!printerName)return{ok:false,error:'No Windows printer queue selected',transport:'windows-raw'};const bytes=bytesFrom(data);const b=bytes.toString('base64');const safe=String(printerName).slice(0,255).replace(/'/g,"''");const ps=`Add-Type -TypeDefinition @'\nusing System;using System.Runtime.InteropServices;public class RawPrinter{[StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]public class DOCINFO{public string pDocName;public string pOutputFile;public string pDataType;}[DllImport("winspool.drv",EntryPoint="OpenPrinterW",SetLastError=true,CharSet=CharSet.Unicode)]public static extern bool OpenPrinter(string n,out IntPtr h,IntPtr p);[DllImport("winspool.drv",SetLastError=true)]public static extern bool ClosePrinter(IntPtr h);[DllImport("winspool.drv",CharSet=CharSet.Unicode,SetLastError=true)]public static extern bool StartDocPrinter(IntPtr h,int l,DOCINFO d);[DllImport("winspool.drv",SetLastError=true)]public static extern bool EndDocPrinter(IntPtr h);[DllImport("winspool.drv",SetLastError=true)]public static extern bool StartPagePrinter(IntPtr h);[DllImport("winspool.drv",SetLastError=true)]public static extern bool EndPagePrinter(IntPtr h);[DllImport("winspool.drv",SetLastError=true)]public static extern bool WritePrinter(IntPtr h,byte[] b,int c,out int w);public static bool Send(string n,byte[] b,out int w){w=0;IntPtr h;if(!OpenPrinter(n,out h,IntPtr.Zero))return false;var d=new DOCINFO();d.pDocName="MK PIZZA POS";d.pDataType="RAW";bool ok=StartDocPrinter(h,1,d)&&StartPagePrinter(h);ok=ok&&WritePrinter(h,b,b.Length,out w);ok=ok&&EndPagePrinter(h)&&EndDocPrinter(h);ClosePrinter(h);return ok;}}\n'@;$b=[Convert]::FromBase64String('${b}');$w=0;if(-not [RawPrinter]::Send('${safe}',$b,[ref]$w)){throw 'Windows RAW printer rejected the job'};Write-Output ('WRITTEN='+$w)`;return{...await psRun(ps),transport:'windows-raw',bytes:bytes.length,printerName}}
function testPayload(label){return Buffer.from([0x1b,0x40,...Buffer.from('MK PIZZA POS\r\n','ascii'),...Buffer.from(`YD801 ${label}\r\n`,'ascii'),0x0a,0x0a])}
async function diagnosticComTest(port,baudRate,signals){return serialSend(port,testPayload(`${port} ${baudRate} D${signals.dtr?1:0}R${signals.rts?1:0}`),baudRate,signals)}
ipcMain.handle('printer:list',()=>listWindowsPrinters());
ipcMain.handle('printer:bluetooth-send',async(_e,{address,data,port,baudRate=9600,dtr=false,rts=false}={})=>port?serialSend(port,data,baudRate,{dtr,rts}):{ok:false,transport:'bluetooth-spp',bluetoothAddress:address||'',error:'No SPP COM port supplied'});
ipcMain.handle('printer:print',async(_e,{address,data,port,baudRate=9600,printerName,transport='serial',dtr=false,rts=false}={})=>{if(printerName){const q=await queueSend(printerName,data);if(q.ok)return q;if(transport==='windows-raw')return q}const selected=safePort(port);if(selected)return serialSend(selected,data,baudRate,{dtr,rts});return{ok:false,transport:'none',bluetoothAddress:address||'',error:'No selected YD801 COM port and Windows printer queue failed'}});
ipcMain.handle('printer:test-serial',async(_e,{address,port,baudRate=9600,printerName,allPorts=true}={})=>{const results=[];if(printerName){const q=await queueSend(printerName,testPayload('WINDOWS-RAW'));results.push(q);if(q.ok&&!allPorts)return{...q,diagnostics:results}}const ports=[port,...(allPorts?await getComPorts():[])].map(safePort).filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i);const rates=allPorts?[Number(baudRate)||9600,115200,460800]:[Number(baudRate)||9600];for(const p of ports){for(const rate of [...new Set(rates)]){for(const signals of allPorts?[{dtr:false,rts:false},{dtr:true,rts:true}]:[{dtr:false,rts:false}]){const r=await diagnosticComTest(p,rate,signals);results.push(r);if(r.ok)return{...r,diagnostics:results}}}}return{ok:false,transport:'diagnostic',bluetoothAddress:address||'',error:'No working serial transport found',diagnostics:results}});
ipcMain.handle('printer:print-raw',(_e,{printerName,data}={})=>queueSend(printerName,data));
ipcMain.handle('printer:print-html',async()=>({ok:false,reason:'html-print-disabled-use-raw'}));
app.on('before-quit',()=>{try{close()}catch{}});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
