(() => {
  const KEY = 'findupto-pos-v3';
  const css = `.ai-copilot{position:fixed;right:22px;bottom:22px;z-index:99999;font-family:Inter,system-ui,sans-serif}.ai-copilot button{border:0;cursor:pointer}.ai-fab{width:54px;height:54px;border-radius:50%;background:#111827;color:#fff;box-shadow:0 10px 30px #0003;font-size:22px}.ai-panel{display:none;position:absolute;right:0;bottom:66px;width:360px;max-height:70vh;overflow:auto;background:#fff;border:1px solid #e5e7eb;border-radius:18px;box-shadow:0 20px 60px #0003;padding:18px}.ai-panel.open{display:block}.ai-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.ai-title{font-weight:800;font-size:16px}.ai-sub{font-size:11px;color:#6b7280}.ai-close{background:#f3f4f6;border-radius:8px;padding:6px 9px}.ai-run{width:100%;padding:11px;border-radius:10px;background:#111827;color:#fff;font-weight:700;margin:8px 0 14px}.ai-metrics{display:grid;grid-template-columns:1fr 1fr;gap:8px}.ai-metric{background:#f8fafc;border-radius:10px;padding:10px}.ai-metric b{display:block;font-size:17px}.ai-metric span{font-size:10px;color:#6b7280}.ai-section{margin-top:15px}.ai-section h4{margin:0 0 7px;font-size:12px}.ai-item{padding:9px 10px;border-left:3px solid #111827;background:#f9fafb;border-radius:7px;margin:6px 0;font-size:12px;line-height:1.4}.ai-item.high{border-left-color:#dc2626}.ai-note{font-size:10px;color:#6b7280;margin-top:12px;line-height:1.4}`;
  const style = document.createElement('style'); style.textContent = css; document.head.appendChild(style);
  const root = document.createElement('div'); root.className = 'ai-copilot'; root.innerHTML = `<button class="ai-fab" aria-label="AI Business Copilot">✦</button><div class="ai-panel"><div class="ai-head"><div><div class="ai-title">AI Business Copilot</div><div class="ai-sub">Private local intelligence</div></div><button class="ai-close">×</button></div><button class="ai-run">Analyze my business</button><div class="ai-result"><div class="ai-note">AI is ready. It analyzes your POS data locally and does not send business data to a third party.</div></div></div>`; document.body.appendChild(root);
  const panel = root.querySelector('.ai-panel'), result = root.querySelector('.ai-result');
  root.querySelector('.ai-fab').onclick = () => panel.classList.toggle('open'); root.querySelector('.ai-close').onclick = () => panel.classList.remove('open');
  function state() { try { return JSON.parse(localStorage.getItem(KEY) || '{}'); } catch { return {}; } }
  function money(v) { return Number(v || 0).toLocaleString(undefined,{maximumFractionDigits:2}); }
  function render(r) { result.innerHTML = `<div class="ai-metrics"><div class="ai-metric"><b>${money(r.metrics.revenue)}</b><span>Revenue</span></div><div class="ai-metric"><b>${r.metrics.transactions}</b><span>Transactions</span></div><div class="ai-metric"><b>${money(r.metrics.averageTicket)}</b><span>Avg. ticket</span></div><div class="ai-metric"><b>${r.metrics.lowStock}</b><span>Low stock</span></div></div>${r.bestSellers?.length?`<div class="ai-section"><h4>🏆 Best sellers</h4>${r.bestSellers.map(x=>`<div class="ai-item"><b>${x.name}</b> — ${x.quantity} sold</div>`).join('')}</div>`:''}${r.warnings?.length?`<div class="ai-section"><h4>⚠️ Attention</h4>${r.warnings.map(x=>`<div class="ai-item">${x}</div>`).join('')}</div>`:''}${r.recommendations?.length?`<div class="ai-section"><h4>💡 Recommended actions</h4>${r.recommendations.map(x=>`<div class="ai-item ${x.priority==='high'?'high':''}"><b>${x.action}</b><br>${x.detail}</div>`).join('')}</div>`:''}<div class="ai-note">Confidence: ${r.confidence}. ${r.note}</div>`; }
  root.querySelector('.ai-run').onclick = async () => { const btn = root.querySelector('.ai-run'); btn.disabled = true; btn.textContent = 'Analyzing…'; try { const s = state(); const api = window.mkPosDesktop?.ai; if (api?.analyze) render(await api.analyze(s)); else { result.innerHTML = '<div class="ai-note">Desktop AI engine is unavailable in browser-only mode. Launch the Electron POS to enable local AI analytics.</div>'; } } catch (e) { result.innerHTML = `<div class="ai-item high">AI analysis failed safely: ${String(e.message || e)}</div>`; } finally { btn.disabled = false; btn.textContent = 'Analyze my business'; } };
})();
