const KEY='findupto-pos-v3',BACKUP='findupto-pos-ai-autopilot-backup-v1';
const db=()=>window.mkPosDesktop?.database||null;
const load=()=>{try{const d=db(),x=d?.loadState?.();if(x)return x;const r=localStorage.getItem(KEY);return r?JSON.parse(r):null}catch{return null}};
const save=s=>{try{const d=db();if(d?.saveState){d.saveState(s,'offline-ai-autopilot');return true}localStorage.setItem(KEY,JSON.stringify(s));return true}catch{return false}};
const n=v=>Number.isFinite(Number(v))?Number(v):0;
const arr=(s,k)=>Array.isArray(s?.[k])?s[k]:[];
const admin=()=>/admin|owner/i.test(document.querySelector('.user-chip small')?.textContent||'');
const enabled=s=>s?.settings?.aiAutoPilot!==false&&s?.settings?.aiEnabled!==false;
const log=(s,text)=>({...s,audit:[...arr(s,'audit'),{id:`AI-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,date:new Date().toLocaleString(),action:text,by:'offline-ai-autopilot'}]});
function backup(s){try{localStorage.setItem(BACKUP,JSON.stringify({at:new Date().toISOString(),state:s}));return true}catch{return false}}
function diagnose(s){const issues=[],warnings=[];const products=arr(s,'products'),orders=arr(s,'heldOrders'),sales=arr(s,'sales');const ids=new Set(),skus=new Set(),bars=new Set();products.forEach((p,i)=>{if(!p.id)issues.push(`product-${i}-missing-id`);else if(ids.has(p.id))issues.push(`duplicate-product-${p.id}`);ids.add(p.id);if(p.sku){if(skus.has(p.sku))issues.push(`duplicate-sku-${p.sku}`);skus.add(p.sku)}if(p.barcode){if(bars.has(p.barcode))issues.push(`duplicate-barcode-${p.barcode}`);bars.add(p.barcode)}if(!p.name)issues.push(`product-${p.id||i}-missing-name`);if(n(p.price)<0||n(p.cost)<0||n(p.stock)<0)issues.push(`product-${p.id||i}-negative-value`);if(p.active!==false&&!p.isDeal&&n(p.stock)<=3)warnings.push(`Low stock: ${p.name||p.id} (${n(p.stock)})`)});const pids=new Set(products.map(p=>p.id));[...orders,...sales].forEach(o=>(Array.isArray(o.items)?o.items:[]).forEach(i=>{if(i.productId&&!pids.has(i.productId))issues.push(`broken-product-reference-${o.invoice||o.id}`);if(n(i.qty)<=0)issues.push(`invalid-quantity-${o.invoice||o.id}`)}));orders.forEach(o=>{if(!o.id||!o.invoice)issues.push(`order-${o.id||'unknown'}-missing-identity`);if(n(o.total)<0)issues.push(`order-${o.invoice||o.id}-negative-total`);if(o.status==='PENDING'&&o.createdAt&&Date.now()-new Date(o.createdAt).getTime()>6*60*60*1000)warnings.push(`Stale order: ${o.invoice||o.id}`)});return{issues:[...new Set(issues)],warnings:[...new Set(warnings)]}}
function repair(s){let x=JSON.parse(JSON.stringify(s||{})),changes=[];['products','customers','suppliers','staff','sales','purchases','expenses','payments','deals','inventoryMoves','heldOrders','accounts','audit'].forEach(k=>{if(!Array.isArray(x[k])){x[k]=[];changes.push(`restored ${k}`)}});x.settings={...(x.settings||{}),aiName:String(x.settings?.aiName||'Findupto AI'),aiInstructions:String(x.settings?.aiInstructions||'')};const ids=new Set();x.products=x.products.map((p,i)=>{const q={...p};if(!q.id){q.id=`AI-PRD-${i+1}`;changes.push(`generated product ID for ${q.name||i+1}`)}if(ids.has(q.id)){q.id=`${q.id}-AI-${i+1}`;changes.push(`repaired duplicate product ID for ${q.name||i+1}`)}ids.add(q.id);if(!q.name){q.name=`Unnamed Product ${i+1}`;changes.push(`named product ${q.id}`)}q.price=Math.max(0,n(q.price));q.cost=Math.max(0,n(q.cost));q.stock=Math.max(0,n(q.stock));return q});const pids=new Set(x.products.map(p=>p.id));const fix=o=>({...o,id:o.id||`AI-ORD-${Date.now()}`,invoice:o.invoice||`FP-AI-${Date.now()}`,items:(Array.isArray(o.items)?o.items:[]).filter(i=>!i.productId||pids.has(i.productId)).map(i=>({...i,qty:Math.max(0,n(i.qty)),price:Math.max(0,n(i.price)),total:Math.max(0,n(i.qty))*Math.max(0,n(i.price))}))});x.heldOrders=x.heldOrders.map(fix);x.sales=x.sales.map(fix);if(changes.length)x=log(x,`${x.settings.aiName} automatically repaired ${changes.length} safe data issue(s)`);return{x,changes}}
function dailyBackup(s){const day=new Date().toISOString().slice(0,10),key=`findupto-ai-backup-day-${day}`;if(localStorage.getItem(key))return;try{localStorage.setItem(BACKUP,JSON.stringify({at:new Date().toISOString(),state:s}));localStorage.setItem(key,'1')}catch{}}
function notify(text,kind='info'){let el=document.getElementById('ai-autopilot-alert');if(!el){el=document.createElement('div');el.id='ai-autopilot-alert';el.style.cssText='position:fixed;left:20px;bottom:20px;z-index:99998;max-width:420px;padding:11px 14px;border:1px solid #30384a;border-radius:12px;background:#111620;color:#eef2f7;box-shadow:0 15px 45px #0007;font:12px Arial;transition:.2s';document.body.appendChild(el)}el.textContent=`✦ ${text}`;el.style.opacity='1';clearTimeout(el.__t);el.__t=setTimeout(()=>el.style.opacity='0',6000)}
function run(){const s=load();if(!s||!enabled(s))return;dailyBackup(s);const d=diagnose(s);if(!d.issues.length){if(d.warnings.length&&admin())notify(`${d.warnings.length} proactive warning(s): ${d.warnings.slice(0,2).join(' · ')}`,'warn');return}if(s.settings?.aiAutoRepair===false||!admin())return;const r=repair(s);if(!r.changes.length)return;backup(s);save(r.x);notify(`${r.x.settings.aiName} repaired ${r.changes.length} safe issue(s) automatically.`)}
function boot(){if(window.__finduptoAiAutopilot)return;window.__finduptoAiAutopilot=true;setTimeout(run,2500);setInterval(run,10000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
