import {money} from './posData';

const n=v=>Number(v||0);
export const salesFor=(sales,{from,to,locationId,userId}={})=>(sales||[]).filter(s=>(!from||String(s.date)>=String(from))&&(!to||String(s.date)<=String(to))&&(!locationId||(s.locationId||'MAIN')===locationId)&&(!userId||s.userId===userId));
export const cogsForSale=(sale,products)=> (sale.items||[]).reduce((sum,i)=>{const p=(products||[]).find(x=>x.id===i.productId);return sum+n(i.qty)*n(i.cost??p?.cost)},0);
export const salesAnalytics=(state,filters={})=>{const sales=salesFor(state.sales,filters);let revenue=0,tax=0,discount=0,cogs=0,units=0;const byProduct={};const byCashier={};const byPayment={};for(const s of sales){revenue+=n(s.total);tax+=n(s.tax);discount+=n(s.discount);cogs+=cogsForSale(s,state.products);for(const i of s.items||[]){units+=n(i.qty);const k=i.productId;byProduct[k]??={productId:k,units:0,revenue:0,cogs:0};byProduct[k].units+=n(i.qty);byProduct[k].revenue+=n(i.qty)*n(i.price);byProduct[k].cogs+=n(i.qty)*n(i.cost??state.products?.find(p=>p.id===k)?.cost)}const cashier=s.userName||s.cashier||s.userId||'Unknown';byCashier[cashier]??={cashier,orders:0,revenue:0};byCashier[cashier].orders++;byCashier[cashier].revenue+=n(s.total);for(const p of s.payments||[]){byPayment[p.method]??={method:p.method,amount:0};byPayment[p.method].amount+=n(p.amount)}}return{orders:sales.length,units,revenue,tax,discount,cogs,grossProfit:revenue-cogs,margin:revenue?((revenue-cogs)/revenue)*100:0,averageOrder:sales.length?revenue/sales.length:0,byProduct:Object.values(byProduct).sort((a,b)=>b.revenue-a.revenue),byCashier:Object.values(byCashier).sort((a,b)=>b.revenue-a.revenue),byPayment:Object.values(byPayment).sort((a,b)=>b.amount-a.amount),formatted:{revenue:money(revenue),cogs:money(cogs),grossProfit:money(revenue-cogs)}}};
export const inventoryValuation=(products,lots=[])=>({retail:(products||[]).reduce((a,p)=>a+n(p.stock)*n(p.price),0),cost:(products||[]).reduce((a,p)=>a+n(p.stock)*n(p.cost),0),lots:lots.length,units:lots.reduce((a,l)=>a+n(l.quantity),0)});
export const lowStockReport=(products,threshold=5)=>(products||[]).filter(p=>p.active!==false&&n(p.stock)<=n(p.reorderPoint??threshold)).sort((a,b)=>n(a.stock)-n(b.stock));
export const taxReport=(sales,filters={})=>salesFor(sales,filters).reduce((a,s)=>{a.sales+=n(s.total);a.tax+=n(s.tax);a.net+=n(s.total)-n(s.tax);return a},{sales:0,net:0,tax:0});
export const exportRows=(analytics)=>analytics.byProduct.map(x=>({...x,grossProfit:x.revenue-x.cogs,margin:x.revenue?((x.revenue-x.cogs)/x.revenue)*100:0}));
