import {uid,today} from './posData';

export const REGISTER_STATES=['CLOSED','OPEN','CLOSING'];
export const createRegisterSession=({registerId,locationId='MAIN',employeeId,openingFloat=0,user}={})=>({id:uid('REGS'),registerId,locationId,employeeId,openingFloat:Number(openingFloat)||0,state:'OPEN',openedAt:new Date().toISOString(),openedBy:user?.username||'system',cashDrops:[],payouts:[],transactions:[]});
export const recordCashDrop=(session,amount,reason='',user)=>({...session,cashDrops:[...(session.cashDrops||[]),{id:uid('DROP'),amount:Math.max(0,Number(amount)||0),reason,date:new Date().toISOString(),by:user?.username||'system'}]});
export const recordPayout=(session,amount,reason='',user)=>({...session,payouts:[...(session.payouts||[]),{id:uid('PAY'),amount:Math.max(0,Number(amount)||0),reason,date:new Date().toISOString(),by:user?.username||'system'}]});
export const addCashTransaction=(session,{type='SALE',amount=0,reference=''}={})=>({...session,transactions:[...(session.transactions||[]),{id:uid('CTX'),type,amount:Number(amount)||0,reference,date:new Date().toISOString()}]});
export const expectedCash=(session)=>Number(session?.openingFloat||0)+(session?.transactions||[]).filter(t=>t.type==='SALE'||t.type==='REFUND_CASH').reduce((s,t)=>s+Number(t.amount||0),0)-(session?.transactions||[]).filter(t=>t.type==='REFUND'||t.type==='PAYOUT').reduce((s,t)=>s+Math.abs(Number(t.amount||0)),0)-(session?.cashDrops||[]).reduce((s,x)=>s+Number(x.amount||0),0)-(session?.payouts||[]).reduce((s,x)=>s+Number(x.amount||0),0);
export const cashCount=(session,counted,user)=>{const expected=expectedCash(session),actual=Math.max(0,Number(counted)||0);return{...session,state:'CLOSED',closedAt:new Date().toISOString(),closedBy:user?.username||'system',countedCash:actual,expectedCash:expected,overShort:actual-expected}};
export const registerZReport=(session)=>({registerId:session.registerId,locationId:session.locationId,sessionId:session.id,openedAt:session.openedAt,closedAt:session.closedAt,openingFloat:Number(session.openingFloat||0),cashSales:(session.transactions||[]).filter(t=>t.type==='SALE').reduce((s,t)=>s+Number(t.amount||0),0),refunds:(session.transactions||[]).filter(t=>t.type==='REFUND'||t.type==='REFUND_CASH').reduce((s,t)=>s+Math.abs(Number(t.amount||0)),0),drops:(session.cashDrops||[]).reduce((s,x)=>s+Number(x.amount||0),0),payouts:(session.payouts||[]).reduce((s,x)=>s+Number(x.amount||0),0),expectedCash:Number(session.expectedCash||expectedCash(session)),countedCash:Number(session.countedCash||0),overShort:Number(session.overShort||0),date:today()});
export const registerReconciliation=(sessions=[])=>sessions.reduce((a,s)=>{a.sessions++;a.sales+=Number(s.transactions?.filter(t=>t.type==='SALE').reduce((x,t)=>x+Number(t.amount||0),0)||0);a.overShort+=Number(s.overShort||0);if(Math.abs(Number(s.overShort||0))>.01)a.varianceSessions++;return a},{sessions:0,sales:0,overShort:0,varianceSessions:0});
