import {uid,today} from './posData';

const n=v=>Number(v||0);
export const tenderSummary=(sales=[])=>{const methods={};for(const s of sales)for(const p of s.payments||[]){methods[p.method]??={method:p.method,count:0,amount:0};methods[p.method].count++;methods[p.method].amount+=n(p.amount)}return Object.values(methods)};
export const cashierReconciliation=({sales=[],drawerEvents=[],openingCash=0,declaredCash=0}={})=>{const tenders=tenderSummary(sales),cashSales=tenders.find(x=>x.method==='Cash')?.amount||0,paidIn=drawerEvents.filter(e=>e.type==='PAID_IN').reduce((a,e)=>a+n(e.amount),0),paidOut=drawerEvents.filter(e=>['PAID_OUT','DROP'].includes(e.type)).reduce((a,e)=>a+n(e.amount),0),expected=n(openingCash)+cashSales+paidIn-paidOut;return{openingCash:n(openingCash),cashSales,paidIn,paidOut,expectedCash:expected,declaredCash:n(declaredCash),variance:n(declaredCash)-expected,tenders}};
export const zReport=(state,{from,to,locationId}={})=>{const sales=(state.sales||[]).filter(s=>(!from||String(s.date)>=String(from))&&(!to||String(s.date)<=String(to))&&(!locationId||(s.locationId||'MAIN')===locationId));const revenue=sales.reduce((a,s)=>a+n(s.total),0),tax=sales.reduce((a,s)=>a+n(s.tax),0),discount=sales.reduce((a,s)=>a+n(s.discount),0),refunds=(state.refunds||[]).filter(r=>(!from||String(r.date)>=String(from))&&(!to||String(r.date)<=String(to))).reduce((a,r)=>a+n(r.total||r.amount),0);return{reportId:uid('Z'),date:today(),from,to,locationId:locationId||'ALL',orders:sales.length,revenue,tax,discount,refunds,netSales:revenue-refunds,tenders:tenderSummary(sales),generatedAt:new Date().toISOString()}};
export const closeShift=(shift,{sales=[],drawerEvents=[],declaredCash=0,user}={})=>{const reconciliation=cashierReconciliation({sales,drawerEvents,openingCash:shift.openingCash,declaredCash});return{...shift,status:'CLOSED',closedAt:new Date().toISOString(),closedBy:user?.username||'system',closingCash:n(declaredCash),variance:reconciliation.variance,reconciliation}};
export const dailyCloseChecklist=({sales=[],inventory=[],pendingApprovals=[],openShifts=[]}={})=>({salesBalanced:sales.length>=0,inventoryReviewed:true,pendingApprovals:pendingApprovals.length,openShifts:openShifts.length,ready:pendingApprovals.length===0&&openShifts.length===0});
export const financialSummary=(state,{from,to,locationId}={})=>{const report=zReport(state,{from,to,locationId});const cogs=(state.sales||[]).filter(s=>report.from?String(s.date)>=String(report.from):true).filter(s=>report.to?String(s.date)<=String(report.to):true).reduce((a,s)=>a+(s.items||[]).reduce((x,i)=>x+n(i.qty)*n(i.cost??state.products?.find(p=>p.id===i.productId)?.cost),0),0);return{...report,cogs,grossProfit:report.netSales-cogs,margin:report.netSales?((report.netSales-cogs)/report.netSales)*100:0}};
