import {salesAnalytics,inventoryValuation,lowStockReport} from './analyticsEnterprise';
import {syncStats} from './offlineRecovery';
import {payableAging} from './purchasingEnterprise';
import {agingBuckets} from './financialControls';

const n=v=>Number(v||0);
export const enterpriseDashboard=(state,filters={})=>{const a=salesAnalytics(state,filters),inventory=inventoryValuation(state.products,state.lots),lowStock=lowStockReport(state.products),payables=payableAging(state.supplierInvoices||[]),receivables=agingBuckets(state.arInvoices||[]),sync=syncStats(state.syncQueue||[]);return{sales:a,inventory,lowStock,payables,receivables,sync,alerts:{lowStock:lowStock.length,payablesOverdue:payables.filter(x=>x.daysOverdue>0).length,receivablesOutstanding:Object.values(receivables).reduce((x,v)=>x+n(v),0),syncFailures:sync.failed+sync.conflicts}}};
export const dashboardKpis=dashboard=>({revenue:n(dashboard.sales.revenue),grossProfit:n(dashboard.sales.grossProfit),margin:n(dashboard.sales.margin),orders:n(dashboard.sales.orders),inventoryCost:n(dashboard.inventory.cost),lowStock:dashboard.lowStock.length,outstandingAR:n(dashboard.receivables?Object.values(dashboard.receivables).reduce((x,v)=>x+n(v),0):0),overdueAP:dashboard.payables.filter(x=>x.daysOverdue>0).reduce((x,v)=>x+n(v.balance),0),syncIssues:n(dashboard.sync.failed)+n(dashboard.sync.conflicts)});
export const dashboardAlertList=dashboard=>[{key:'low-stock',label:'Low stock items',value:dashboard.alerts.lowStock,severity:dashboard.alerts.lowStock?'warning':'ok'},{key:'payables',label:'Overdue supplier invoices',value:dashboard.alerts.payablesOverdue,severity:dashboard.alerts.payablesOverdue?'warning':'ok'},{key:'receivables',label:'Outstanding customer balance',value:dashboard.alerts.receivablesOutstanding,severity:dashboard.alerts.receivablesOutstanding?'info':'ok'},{key:'sync',label:'Offline sync issues',value:dashboard.alerts.syncFailures,severity:dashboard.alerts.syncFailures?'critical':'ok'}];
