import {uid,today} from './posData';

export const STOCK_MOVEMENTS=['RECEIVE','SALE','RETURN','TRANSFER_OUT','TRANSFER_IN','ADJUSTMENT','WASTE','COUNT'];
export const createInventoryLocation=({name='Main Warehouse',code='MAIN'}={})=>({id:uid('LOC'),name,code,active:true});
export const createStockLot=({productId,locationId='MAIN',quantity=0,cost=0,batchNo='',expiryDate=null}={})=>({id:uid('LOT'),productId,locationId,quantity:Number(quantity)||0,cost:Number(cost)||0,batchNo,expiryDate,createdAt:new Date().toISOString()});
export const createStockMovement=({productId,locationId='MAIN',type='ADJUSTMENT',quantity=0,cost=0,reference='',reason='',user}={})=>({id:uid('MOV'),productId,locationId,type,quantity:Number(quantity)||0,cost:Number(cost)||0,reference,reason,date:new Date().toISOString(),by:user?.username||'system'});
export const applyMovement=(lots,movement)=>{const next=[...(lots||[])];let lot=next.find(l=>l.productId===movement.productId&&l.locationId===movement.locationId&&(!movement.batchNo||l.batchNo===movement.batchNo));const delta=['SALE','TRANSFER_OUT','WASTE'].includes(movement.type)?-Math.abs(Number(movement.quantity||0)):Math.abs(Number(movement.quantity||0));if(!lot){lot=createStockLot({productId:movement.productId,locationId:movement.locationId,quantity:0,cost:movement.cost,batchNo:movement.batchNo,expiryDate:movement.expiryDate});next.push(lot)}lot.quantity=Number(lot.quantity||0)+delta;lot.cost=Number(movement.cost||lot.cost||0);return next};
export const transferStock=(lots,movements,{productId,fromLocationId,toLocationId,quantity,cost=0,user}={})=>{const q=Math.abs(Number(quantity)||0);let next=applyMovement(lots,createStockMovement({productId,locationId:fromLocationId,type:'TRANSFER_OUT',quantity:q,cost,user}));next=applyMovement(next,createStockMovement({productId,locationId:toLocationId,type:'TRANSFER_IN',quantity:q,cost,user}));return{lots:next,movements:[...movements,createStockMovement({productId,locationId:fromLocationId,type:'TRANSFER_OUT',quantity:q,cost,reference:`TO:${toLocationId}`,user}),createStockMovement({productId,locationId:toLocationId,type:'TRANSFER_IN',quantity:q,cost,reference:`FROM:${fromLocationId}`,user})]}};
export const stockOnHand=(lots=[],productId,locationId=null)=>lots.filter(l=>l.productId===productId&&(!locationId||l.locationId===locationId)).reduce((s,l)=>s+Number(l.quantity||0),0);
export const lowStock=(products=[],lots=[],locationId=null)=>products.filter(p=>stockOnHand(lots,p.id,locationId)<=Number(p.reorderPoint||p.minStock||0)).map(p=>({...p,stock:stockOnHand(lots,p.id,locationId)}));
export const stockValuation=(lots=[])=>({quantity:lots.reduce((s,l)=>s+Number(l.quantity||0),0),value:lots.reduce((s,l)=>s+Number(l.quantity||0)*Number(l.cost||0),0)});
export const expiryReport=(lots=[],days=30)=>{const now=Date.now(),limit=now+Number(days)*86400000;return{expired:lots.filter(l=>l.expiryDate&&new Date(l.expiryDate).getTime()<now&&Number(l.quantity)>0),expiring:lots.filter(l=>l.expiryDate&&new Date(l.expiryDate).getTime()>=now&&new Date(l.expiryDate).getTime()<=limit&&Number(l.quantity)>0)}};
export const inventoryCount=(lots=[],counts=[])=>{const expected=stockValuation(lots).quantity,counted=(counts||[]).reduce((s,c)=>s+Number(c.quantity||0),0);return{expected,counted,variance:counted-expected,date:today()}};
export const wastage=(movement)=>({...movement,type:'WASTE',quantity:Math.abs(Number(movement.quantity||0)),reason:movement.reason||'Wastage'});
export const automaticSaleDeduction=(lots,items=[],locationId='MAIN')=>{let next=[...(lots||[])],deductions=[];for(const i of items){let remaining=Math.abs(Number(i.qty||0));for(const lot of next.filter(l=>l.productId===i.productId&&l.locationId===locationId&&Number(l.quantity)>0).sort((a,b)=>new Date(a.expiryDate||'2999-12-31')-new Date(b.expiryDate||'2999-12-31'))){if(!remaining)break;const q=Math.min(remaining,Number(lot.quantity));lot.quantity-=q;remaining-=q;deductions.push({productId:i.productId,lotId:lot.id,quantity:q,cost:lot.cost})}}return{lots:next,deductions}};
export const inventorySummary=(products=[],lots=[])=>{const v=stockValuation(lots);return{products:products.length,stockQuantity:v.quantity,stockValue:v.value,lowStock:lowStock(products,lots).length,expired:expiryReport(lots).expired.length,expiring:expiryReport(lots).expiring.length}};
