import {uid,today} from './posData';

export const LOT_STATUS=['ACTIVE','QUARANTINED','EXPIRED','DEPLETED'];
export const createLot=({productId,lotNo,expiryDate,quantity=0,cost=0,supplierId='',locationId='MAIN'})=>({id:uid('LOT'),productId,lotNo:String(lotNo||`LOT-${Date.now()}`),expiryDate:expiryDate||null,receivedAt:new Date().toISOString(),quantity:Math.max(0,Number(quantity)||0),initialQuantity:Math.max(0,Number(quantity)||0),cost:Number(cost)||0,supplierId,locationId,status:'ACTIVE'});
export const lotStatus=lot=>{if(Number(lot.quantity)<=0)return'DEPLETED';if(lot.expiryDate&&new Date(lot.expiryDate)<new Date())return'EXPIRED';return lot.status==='QUARANTINED'?'QUARANTINED':'ACTIVE'};
export const fifoLots=(lots,productId,locationId='MAIN')=>lots.filter(l=>l.productId===productId&&(l.locationId||'MAIN')===locationId&&lotStatus(l)==='ACTIVE').sort((a,b)=>new Date(a.expiryDate||'2999-12-31')-new Date(b.expiryDate||'2999-12-31')||new Date(a.receivedAt)-new Date(b.receivedAt));
export const receiveStock=(state,{productId,quantity,cost,lotNo,expiryDate,supplierId,locationId='MAIN',user})=>{const qty=Math.max(0,Number(quantity)||0);if(!productId||!qty)return state;const lot=createLot({productId,quantity:qty,cost,lotNo,expiryDate,supplierId,locationId});const products=(state.products||[]).map(p=>p.id===productId?{...p,stock:Number(p.stock||0)+qty,lastCost:Number(cost)||p.cost||0}:p);return{...state,products,lots:[...(state.lots||[]),lot],inventoryMoves:[...(state.inventoryMoves||[]),{id:uid('MOVE'),date:today(),type:'RECEIVE',productId,quantity:qty,lotId:lot.id,locationId,cost:Number(cost)||0,by:user?.username||'system'}],audit:[...(state.audit||[]),{id:uid('AUD'),date:today(),action:`Received ${qty} units into ${locationId}${lotNo?` · Lot ${lotNo}`:''}`,by:user?.username||'system'}]}};
export const transferStock=(state,{productId,quantity,fromLocation='MAIN',toLocation,user,note=''})=>{const qty=Math.max(0,Number(quantity)||0);if(!productId||!qty||!toLocation||fromLocation===toLocation)return state;const source=fifoLots(state.lots||[],productId,fromLocation);let remaining=qty;const lots=[...(state.lots||[])];const moves=[];for(const lot of source){if(remaining<=0)break;const take=Math.min(remaining,Number(lot.quantity||0));if(!take)continue;const i=lots.findIndex(x=>x.id===lot.id);lots[i]={...lots[i],quantity:Number(lots[i].quantity)-take,status:Number(lots[i].quantity)-take<=0?'DEPLETED':lots[i].status};const newLot=createLot({productId,quantity:take,cost:lot.cost,lotNo:lot.lotNo,expiryDate:lot.expiryDate,locationId:toLocation});lots.push(newLot);moves.push({id:uid('MOVE'),date:today(),type:'TRANSFER_OUT',productId,quantity:take,lotId:lot.id,fromLocation,toLocation,by:user?.username||'system'},{id:uid('MOVE'),date:today(),type:'TRANSFER_IN',productId,quantity:take,lotId:newLot.id,fromLocation,toLocation,by:user?.username||'system'});remaining-=take}if(remaining>0)return state;return{...state,lots,inventoryMoves:[...(state.inventoryMoves||[]),...moves],audit:[...(state.audit||[]),{id:uid('AUD'),date:today(),action:`Transferred ${qty} units ${fromLocation} → ${toLocation}${note?` · ${note}`:''}`,by:user?.username||'system'}]};};
export const stockByLocation=(lots,productId)=>lots.filter(l=>l.productId===productId).reduce((a,l)=>a+(lotStatus(l)==='ACTIVE'?Number(l.quantity||0):0),0);
export const expiringLots=(lots,days=30)=>{const end=Date.now()+days*86400000;return lots.filter(l=>l.expiryDate&&new Date(l.expiryDate).getTime()<=end&&new Date(l.expiryDate).getTime()>=Date.now()&&Number(l.quantity)>0)};
export const expiredLots=(lots)=>lots.filter(l=>lotStatus(l)==='EXPIRED');
export const createRecipe=({productId,name,items=[],yieldQty=1}={})=>({id:uid('REC'),productId,name:name||'Recipe',yieldQty:Number(yieldQty)||1,items:items.map(i=>({ingredientId:i.ingredientId||i.productId,quantity:Number(i.quantity||i.qty)||0,unit:i.unit||'unit'})),active:true});
export const recipeCost=(recipe,costs={})=>(recipe?.items||[]).reduce((s,i)=>s+Number(i.quantity||0)*Number(costs[i.ingredientId]||0),0)/Math.max(1,Number(recipe?.yieldQty)||1);
export const consumeRecipe=(recipe,quantity,costs={})=>(recipe?.items||[]).map(i=>({ingredientId:i.ingredientId,quantity:Number(i.quantity||0)*Number(quantity||0)/Math.max(1,Number(recipe.yieldQty)||1),cost:Number(i.quantity||0)*Number(quantity||0)/Math.max(1,Number(recipe.yieldQty)||1)*Number(costs[i.ingredientId]||0)}));
export const wastageTransaction=({productId,lotId,quantity,cost,reason='Wastage',user}={})=>({id:uid('WST'),productId,lotId,quantity:Number(quantity)||0,cost:Number(cost)||0,totalCost:(Number(quantity)||0)*(Number(cost)||0),reason,date:today(),by:user?.username||'system'});
export const adjustStock=(lots,{lotId,quantity,reason,user}={})=>(lots||[]).map(l=>l.id===lotId?{...l,quantity:Math.max(0,Number(l.quantity||0)+Number(quantity||0)),lastAdjustment:{quantity:Number(quantity||0),reason:reason||'Adjustment',date:today(),by:user?.username||'system'}}:l);
export const fifoCost=(lots,quantity)=>{let remaining=Math.max(0,Number(quantity)||0),cost=0;for(const l of [...(lots||[])].sort((a,b)=>new Date(a.receivedAt)-new Date(b.receivedAt))){if(remaining<=0)break;const take=Math.min(remaining,Number(l.quantity)||0);cost+=take*Number(l.cost||0);remaining-=take}return{cost,unfulfilled:remaining}};
export const inventoryValue=(lots=[])=>lots.reduce((s,l)=>s+(lotStatus(l)==='ACTIVE'?Number(l.quantity||0)*Number(l.cost||0):0),0);
export const cogsForSale=(sale,recipes={},lotsByProduct={})=>(sale?.items||[]).reduce((s,i)=>{const r=recipes[i.productId],qty=Number(i.qty||0);return s+(r?consumeRecipe(r,qty,Object.fromEntries((lotsByProduct[i.productId]||[]).map(l=>[l.productId,l.cost]))).reduce((a,x)=>a+x.cost,0):fifoCost(lotsByProduct[i.productId]||[],qty).cost)},0);
