import {uid} from './posData';

export const KDS_ITEM_STATES=['NEW','ACCEPTED','PREPARING','READY','SERVED','VOID'];
export const KDS_TICKET_STATES=['NEW','IN_PROGRESS','READY','EXPO','COMPLETED','VOID'];
export const createKitchenStation=({name='Main Kitchen',locationId='MAIN',printerDeviceId=null,displayDeviceId=null}={})=>({id:uid('KST'),name,locationId,printerDeviceId,displayDeviceId,active:true});
export const createKitchenScreen=({name='Kitchen Display',stationId=null,filters=[],sort='OLDEST_FIRST'}={})=>({id:uid('KDS'),name,stationId,filters,sort,active:true});
export const routeKitchenItem=(item,stations=[])=>stations.find(s=>s.id===item.stationId)||stations.find(s=>(s.name||'').toLowerCase()===(item.station||'').toLowerCase())||stations[0]||null;
export const createKitchenTicket=({orderId,orderNo,tableName='',channel='POS,',priority='NORMAL',items=[],course=null}={})=>({id:uid('KIT'),orderId,orderNo,tableName,channel:channel.replace(/,$/,''),priority,course,items:items.map(i=>({id:i.id||uid('KITM'),productId:i.productId,name:i.name,qty:Number(i.qty)||1,stationId:i.stationId||null,notes:i.notes||'',state:'NEW',startedAt:null,readyAt:null})),state:'NEW',createdAt:new Date().toISOString(),bumpedAt:null});
export const updateKitchenItem=(ticket,itemId,state,user)=>({...ticket,items:(ticket.items||[]).map(i=>i.id===itemId?{...i,state,startedAt:state==='PREPARING'?(i.startedAt||new Date().toISOString()):i.startedAt,readyAt:state==='READY'?new Date().toISOString():i.readyAt,updatedBy:user?.username||'system'}:i),state:ticketState(ticket)});
export const ticketState=ticket=>{const items=ticket?.items||[];if(!items.length)return'NEW';if(items.every(i=>i.state==='VOID'))return'VOID';if(items.every(i=>['READY','SERVED','VOID'].includes(i.state)))return'READY';if(items.some(i=>['PREPARING','ACCEPTED','READY'].includes(i.state)))return'IN_PROGRESS';return'NEW'};
export const bumpTicket=ticket=>({...ticket,state:'READY',bumpedAt:new Date().toISOString(),items:(ticket.items||[]).map(i=>i.state==='VOID'?i:{...i,state:'READY',readyAt:i.readyAt||new Date().toISOString()})});
export const recallTicket=ticket=>({...ticket,state:'EXPO',recalledAt:new Date().toISOString()});
export const completeTicket=ticket=>({...ticket,state:'COMPLETED',completedAt:new Date().toISOString(),items:(ticket.items||[]).map(i=>i.state==='VOID'?i:{...i,state:'SERVED'})});
export const kitchenQueue=(tickets=[],stationId=null)=>tickets.filter(t=>t.state!=='COMPLETED'&&t.state!=='VOID').map(t=>({...t,items:stationId?t.items.filter(i=>i.stationId===stationId):t.items})).filter(t=>t.items.length).sort((a,b)=>{const p={URGENT:0,HIGH:1,NORMAL:2,LOW:3};return(p[a.priority]??2)-(p[b.priority]??2)||new Date(a.createdAt)-new Date(b.createdAt)});
export const kitchenTimer=(item,now=new Date())=>{const start=item?.startedAt?new Date(item.startedAt):null;return{running:Boolean(start&&!item.readyAt),minutes:start?Math.max(0,Math.floor(((item.readyAt?new Date(item.readyAt):now)-start)/60000)):0}};
export const kitchenPerformance=(tickets=[],targetMinutes=15)=>{const done=tickets.filter(t=>t.completedAt&&t.createdAt);const minutes=done.map(t=>(new Date(t.completedAt)-new Date(t.createdAt))/60000);return{tickets:tickets.length,completed:done.length,averageMinutes:minutes.length?minutes.reduce((a,b)=>a+b,0)/minutes.length:0,withinTarget:minutes.filter(m=>m<=targetMinutes).length,late:minutes.filter(m=>m>targetMinutes).length}};
export const expoSummary=(tickets=[])=>({new:tickets.filter(t=>t.state==='NEW').length,inProgress:tickets.filter(t=>t.state==='IN_PROGRESS').length,ready:tickets.filter(t=>t.state==='READY').length,expo:tickets.filter(t=>t.state==='EXPO').length,completed:tickets.filter(t=>t.state==='COMPLETED').length});
