import {uid,today} from './posData';

export const createLoyaltyAccount=({customerId,points=0,balance=0,tier='STANDARD'}={})=>({id:uid('LOY'),customerId,points:Number(points)||0,storeCredit:Number(balance)||0,tier,createdAt:new Date().toISOString(),active:true});
export const earnPoints=(account,{amount=0,rate=1,saleId=null,user}={})=>{const earned=Math.max(0,Math.floor(Number(amount||0)*Number(rate||0)));return{...account,points:Number(account.points||0)+earned,lastEarned:{points:earned,saleId,date:today(),by:user?.username||'system'}}};
export const redeemPoints=(account,{points=0,valuePerPoint=0.01,orderId=null,user}={})=>{const p=Math.max(0,Math.floor(Number(points)||0));if(p>Number(account.points||0))return{ok:false,account};const value=p*Number(valuePerPoint||0);return{ok:true,value,account:{...account,points:Number(account.points)-p,lastRedeemed:{points:p,value,orderId,date:today(),by:user?.username||'system'}}}};
export const addStoreCredit=(account,amount,reason='',user)=>{const v=Math.max(0,Number(amount)||0);return{...account,storeCredit:Number(account.storeCredit||0)+v,lastCredit:{amount:v,reason,date:today(),by:user?.username||'system'}}};
export const spendStoreCredit=(account,amount,orderId=null,user)=>{const v=Math.max(0,Number(amount)||0);if(v>Number(account.storeCredit||0))return{ok:false,account};return{ok:true,account:{...account,storeCredit:Number(account.storeCredit)-v,lastSpend:{amount:v,orderId,date:today(),by:user?.username||'system'}}}};
export const createGiftCard=({code,balance=0,customerId=null,expiresAt=null}={})=>({id:uid('GIFT'),code:String(code||uid('GC')).toUpperCase(),balance:Math.max(0,Number(balance)||0),initialBalance:Math.max(0,Number(balance)||0),customerId,expiresAt,active:true,createdAt:new Date().toISOString()});
export const redeemGiftCard=(card,amount,orderId=null,user)=>{if(!card?.active||card.expiresAt&&new Date(card.expiresAt)<new Date())return{ok:false,card};const v=Math.max(0,Number(amount)||0);if(v>Number(card.balance||0))return{ok:false,card};return{ok:true,card:{...card,balance:Number(card.balance)-v,lastRedemption:{amount:v,orderId,date:today(),by:user?.username||'system'}}}};
export const customerValue=(sales,customerId)=>{const s=(sales||[]).filter(x=>x.customerId===customerId);return{orders:s.length,revenue:s.reduce((a,x)=>a+Number(x.total||0),0),lastOrder:s.sort((a,b)=>String(b.date).localeCompare(String(a.date)))[0]?.date||null}};
