import {uid,today} from './posData';

export const PROMO_TYPES=['PERCENT','FIXED','BOGO','BUNDLE','HAPPY_HOUR','FREE_ITEM'];
export const createLoyaltyProgram=({name='Rewards',pointsPerCurrency=1,tiers=[]}={})=>({id:uid('LOY'),name,pointsPerCurrency:Number(pointsPerCurrency)||1,tiers,active:true});
export const createLoyaltyAccount=({customerId,points=0,tier='STANDARD'}={})=>({id:uid('LAC'),customerId,points:Number(points)||0,tier,createdAt:new Date().toISOString(),active:true});
export const earnPoints=(account,amount,program)=>({...account,points:Number(account.points||0)+Math.max(0,Math.floor(Number(amount||0)*Number(program?.pointsPerCurrency||1)))}) ;
export const redeemPoints=(account,points)=>{const p=Math.max(0,Math.floor(Number(points)||0));return{account:{...account,points:Math.max(0,Number(account.points||0)-p)},redeemed:Math.min(p,Number(account.points||0))}};
export const updateLoyaltyTier=(account,tiers=[],lifetimeSpend=0)=>{const sorted=[...(tiers||[])].sort((a,b)=>Number(b.minSpend||0)-Number(a.minSpend||0));const tier=sorted.find(t=>Number(lifetimeSpend)>=Number(t.minSpend||0));return{...account,tier:tier?.name||account.tier}};
export const createPromotion=(data={})=>({id:uid('PRO'),name:data.name||'Promotion',type:data.type||'PERCENT',value:Number(data.value)||0,minOrder:Number(data.minOrder)||0,productIds:data.productIds||[],categoryIds:data.categoryIds||[],days:data.days||[0,1,2,3,4,5,6],startTime:data.startTime||null,endTime:data.endTime||null,code:data.code||'',usageLimit:data.usageLimit==null?null:Number(data.usageLimit),perCustomerLimit:data.perCustomerLimit==null?null:Number(data.perCustomerLimit),usedCount:0,startsAt:data.startsAt||null,endsAt:data.endsAt||null,active:true});
export const promotionEligible=(promo,{subtotal=0,productIds=[],categoryIds=[],customerId=null,now=new Date(),usageByCustomer={}}={})=>{if(!promo?.active||subtotal<Number(promo.minOrder||0))return false;if(promo.startsAt&&now<new Date(promo.startsAt)||promo.endsAt&&now>new Date(promo.endsAt))return false;if(promo.usageLimit!=null&&promo.usedCount>=promo.usageLimit)return false;if(customerId&&promo.perCustomerLimit!=null&&(usageByCustomer[customerId]||0)>=promo.perCustomerLimit)return false;if(promo.productIds.length&&!productIds.some(id=>promo.productIds.includes(id)))return false;if(promo.categoryIds.length&&!categoryIds.some(id=>promo.categoryIds.includes(id)))return false;const day=now.getDay();if(!promo.days.includes(day))return false;const mins=now.getHours()*60+now.getMinutes(),parse=s=>s?Number(s.split(':')[0])*60+Number(s.split(':')[1]):null;const st=parse(promo.startTime),en=parse(promo.endTime);return!(st!=null&&en!=null&&(mins<st||mins>en))};
export const promotionDiscount=(promo,subtotal)=>promo.type==='PERCENT'?Math.min(Number(subtotal||0),Number(subtotal||0)*Number(promo.value||0)/100):promo.type==='FIXED'?Math.min(Number(subtotal||0),Number(promo.value||0)):0;
export const createCoupon=(code,promotionId,{expiresAt=null,usageLimit=1}={})=>({id:uid('CPN'),code:String(code||'').toUpperCase(),promotionId,expiresAt,usageLimit:Number(usageLimit)||1,usedCount:0,active:true});
export const redeemCoupon=(coupon)=>coupon?.active&&(!coupon.expiresAt||new Date(coupon.expiresAt)>=new Date())&&coupon.usedCount<coupon.usageLimit?{...coupon,usedCount:coupon.usedCount+1}:null;
export const createGiftCard=({code,balance=0,expiresAt=null}={})=>({id:uid('GFT'),code:code||uid('GC'),initialBalance:Number(balance)||0,balance:Number(balance)||0,expiresAt,active:true,createdAt:new Date().toISOString()});
export const redeemGiftCard=(card,amount)=>{const a=Math.min(Math.max(0,Number(amount)||0),Number(card?.balance||0));return{card:{...card,balance:Number(card.balance||0)-a},redeemed:a}};
export const giftCardValid=(card,now=new Date())=>Boolean(card?.active&&Number(card.balance)>0&&(!card.expiresAt||new Date(card.expiresAt)>=now));
export const bogoDiscount=(items=[],buy=1,get=1)=>{let remaining=items.map(i=>({...i,qty:Number(i.qty)||0}));let free=0;for(const i of remaining){const sets=Math.floor(i.qty/(buy+get));free+=sets*get}return free};
export const loyaltySummary=(accounts=[],promotions=[],giftCards=[])=>({members:accounts.length,totalPoints:accounts.reduce((s,a)=>s+Number(a.points||0),0),activePromotions:promotions.filter(p=>p.active).length,giftCards:giftCards.filter(giftCardValid).length,giftCardBalance:giftCards.reduce((s,g)=>s+Number(g.balance||0),0),date:today()});
