import {uid} from './posData';

export const PRODUCT_TYPES=['PRODUCT','SERVICE','COMBO'];
export const createProduct=(data={})=>({id:data.id||uid('PRD'),name:data.name||'New Product',sku:data.sku||uid('SKU'),barcode:data.barcode||'',type:data.type||'PRODUCT',categoryId:data.categoryId||null,description:data.description||'',image:data.image||'',price:Number(data.price)||0,cost:Number(data.cost)||0,taxCode:data.taxCode||null,allergens:data.allergens||[],nutrition:data.nutrition||{},variants:data.variants||[],modifierGroups:data.modifierGroups||[],available:data.available!==false,availability:data.availability||null,createdAt:new Date().toISOString()});
export const createVariant=({name,sku='',barcode='',priceDelta=0,cost=0,attributes={}}={})=>({id:uid('VAR'),name:name||'Variant',sku:sku||uid('SKU'),barcode,priceDelta:Number(priceDelta)||0,cost:Number(cost)||0,attributes,active:true});
export const createModifierGroup=({name,required=false,min=0,max=1,modifiers=[]}={})=>({id:uid('MODG'),name:name||'Modifier Group',required,min:Number(min)||0,max:Number(max)||1,modifiers:modifiers.map(m=>({id:m.id||uid('MOD'),name:m.name||'Option',price:Number(m.price)||0,sku:m.sku||'',active:m.active!==false}))});
export const createCombo=({name,items=[],price=0}={})=>({id:uid('COM'),name:name||'Combo',type:'COMBO',items:items.map(i=>({productId:i.productId,quantity:Number(i.quantity||i.qty)||1,allowedVariants:i.allowedVariants||[]})),price:Number(price)||0,active:true});
export const productPrice=(product,{variantId=null,modifiers=[]}={})=>{const v=(product?.variants||[]).find(x=>x.id===variantId);return Number(product?.price||0)+Number(v?.priceDelta||0)+(modifiers||[]).reduce((s,m)=>s+Number(m.price||0),0)};
export const validateModifiers=(product,selected={})=>{const errors=[];for(const g of product?.modifierGroups||[]){const n=(selected[g.id]||[]).length;if(g.required&&n<g.min)errors.push(`${g.name}: minimum ${g.min}`);if(n>g.max)errors.push(`${g.name}: maximum ${g.max}`)}return{valid:!errors.length,errors}};
export const productAvailable=(product,date=new Date())=>{if(product?.available===false)return false;const a=product?.availability;if(!a)return true;const day=a.days?.length?!a.days.includes(date.getDay()):true;const mins=date.getHours()*60+date.getMinutes(),parse=s=>s?Number(s.split(':')[0])*60+Number(s.split(':')[1]):null;const start=parse(a.startTime),end=parse(a.endTime);return day&&!(start!=null&&end!=null&&(mins<start||mins>end))};
export const categoryTree=(categories=[])=>{const map=Object.fromEntries(categories.map(c=>[c.id,{...c,children:[]}])) ;const roots=[];for(const c of categories){if(c.parentId&&map[c.parentId])map[c.parentId].children.push(map[c.id]);else if(map[c.id])roots.push(map[c.id])}return roots};
export const reorderMenu=(products,orderedIds)=>{const rank=new Map(orderedIds.map((id,i)=>[id,i]));return[...(products||[])].sort((a,b)=>(rank.get(a.id)??999999)-(rank.get(b.id)??999999)).map((p,i)=>({...p,sortOrder:i}))};
export const menuSearch=(products,query='')=>{const q=String(query).trim().toLowerCase();return(products||[]).filter(p=>!q||[p.name,p.sku,p.barcode,p.description].some(v=>String(v||'').toLowerCase().includes(q)))};
export const allergenSummary=products=>Object.values((products||[]).reduce((a,p)=>{for(const x of p.allergens||[]){a[x]??={allergen:x,products:0};a[x].products++}return a},{}));
export const menuAvailability=(products,date=new Date())=>(products||[]).map(p=>({...p,isAvailable:productAvailable(p,date)}));
