export const DEFAULT_BUSINESS={name:'MK Pizza & Ice Bar',address:'Collage Road Abbas Chowk, Bhakkar, Pakistan',phone:'0316 9700025',currency:'Rs.',tax:0};
export const USERS=[{username:'admin',role:'Admin',password:'0099'},{username:'owner',role:'Owner',password:'0099'},{username:'cashier',role:'Cashier',password:'0099'},{username:'accountant',role:'Accountant',password:'0099'}];
export const SEED_PRODUCTS=[{id:'PIZ-001',name:'Chicken Pizza',category:'Pizza',sku:'PIZ-001',barcode:'100001',price:850,cost:500,stock:25,active:true,tax:0,variants:[]},{id:'BUR-001',name:'Beef Burger',category:'Burgers',sku:'BUR-001',barcode:'100002',price:550,cost:300,stock:18,active:true,tax:0,variants:[]},{id:'SID-001',name:'Fries',category:'Sides',sku:'SID-001',barcode:'100003',price:250,cost:120,stock:40,active:true,tax:0,variants:[]},{id:'ICE-001',name:'Vanilla Ice Cream',category:'Ice Cream',sku:'ICE-001',barcode:'100004',price:220,cost:90,stock:30,active:true,tax:0,variants:[]},{id:'DRK-001',name:'Cold Drink',category:'Drinks',sku:'DRK-001',barcode:'100005',price:100,cost:55,stock:60,active:true,tax:0,variants:[]}];
export const SEED_CUSTOMERS=[{id:'C-001',name:'Walk-in Customer',phone:'',email:'',address:'',balance:0,points:0,active:true},{id:'C-002',name:'Ahmed Traders',phone:'0300-1234567',email:'',address:'',balance:0,points:820,active:true},{id:'C-003',name:'Sara Khan',phone:'0312-9876543',email:'',address:'',balance:1250,points:240,active:true}];
export const SEED_SUPPLIERS=[];
export const SEED_STAFF=[];
export const STORAGE_KEY='findupto-pos-v3';
export const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
export const today=()=>new Date().toLocaleString();
export const money=n=>`${DEFAULT_BUSINESS.currency} ${Number(n||0).toLocaleString()}`;
export const parseCSV=text=>{const rows=[];let row=[],cell='',quoted=false;const input=String(text??'').replace(/^\uFEFF/,'');for(let i=0;i<input.length;i++){const c=input[i],n=input[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++;continue}if(c==='"'){quoted=!quoted;continue}if(c===','&&!quoted){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(v=>String(v).trim()!==''))rows.push(row);row=[];continue}cell+=c}if(cell!==''||row.length){row.push(cell);if(row.some(v=>String(v).trim()!==''))rows.push(row)}return rows};
export const downloadText=(filename,text,mime='text/plain')=>{const blob=new Blob([String(text??'')],{type:`${mime};charset=utf-8`});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const variantList=v=>Array.isArray(v)?v:Array.isArray(v?.options)?v.options:Array.isArray(v?.items)?v.items:Array.isArray(v?.values)?v.values:Array.isArray(v?.variants)?v.variants:Array.isArray(v?.children)?v.children:[];
const normalizeVariant=(p,v,i,groupName='')=>{if(typeof v==='string')return{id:`${p?.id||'variant'}-${i}`,name:groupName?`${groupName}: ${v}`:v,price:p?.price,stock:p?.stock,active:true};const name=v?.name??v?.label??v?.title??v?.value??`Variant ${i+1}`;return{...v,id:v?.id||`${p?.id||'variant'}-${i}`,name:groupName&&name!==groupName?`${groupName}: ${name}`:name,price:v?.price??v?.amount??v?.sellingPrice??p?.price,stock:v?.stock??v?.quantity??v?.qty??v?.inventory,active:v?.active!==false}};
export const variantsOf=p=>{const raw=p?.variants??p?.variantOptions??p?.options??p?.sizes??p?.variations??[];if(!raw)return[];if(Array.isArray(raw)){const nested=raw.some(v=>v&&typeof v==='object'&&(Array.isArray(v.options)||Array.isArray(v.items)||Array.isArray(v.values)||Array.isArray(v.children)));if(nested){let out=[];raw.forEach((group,gi)=>{const groupName=group?.name??group?.label??group?.title??`Option ${gi+1}`;variantList(group).forEach((v,vi)=>out.push(normalizeVariant(p,v,out.length,groupName)))});return out.filter(Boolean)}return raw.map((v,i)=>normalizeVariant(p,v,i)).filter(Boolean)}return variantList(raw).map((v,i)=>normalizeVariant(p,v,i)).filter(Boolean)};
export const hasVariants=p=>variantsOf(p).length>0;
export const variantPrice=(p,v)=>Number(v?.price??p?.price??0);
export const variantStock=(p,v)=>{const raw=v?.stock;if(raw===undefined||raw===null||String(raw).trim()==='')return Math.max(0,Number(p?.stock||0));return Math.max(0,Number(raw||0))};

const desktopDb=()=>typeof window!=='undefined'&&window.mkPosDesktop?.database?.loadState?window.mkPosDesktop.database:null;
export const loadState=()=>{try{const db=desktopDb();const persisted=db?.loadState?.();if(persisted)return persisted;const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):null}catch{try{const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):null}catch{return null}}};
export const saveState=s=>{try{const db=desktopDb();if(db?.saveState){const actor=s?.currentUser?.username||'system';db.saveState(s,actor);return}localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}catch{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}catch{}}};

export const DEFAULT_AI={name:'Findupto AI',enabled:true,autopilot:true,autoRepair:true,allowCashierActions:false,instructions:'Protect business data, never invent transactions, explain risky actions, prefer reversible fixes, and require Admin/Owner approval for destructive actions.'};
export const aiSettings=s=>({...DEFAULT_AI,...(s?.settings?.ai||{})});
export const aiRoleCan=(role,action)=>{if(action==='read'||action==='diagnose'||action==='suggest')return true;if(action==='repair')return role==='Admin'||role==='Owner';if(action==='transaction')return role==='Admin'||role==='Owner'||role==='Cashier';return false};
export const aiDiagnostics=s=>{const issues=[];const products=Array.isArray(s?.products)?s.products:[];const orders=Array.isArray(s?.heldOrders)?s.heldOrders:[];const customers=Array.isArray(s?.customers)?s.customers:[];products.forEach(p=>{if(!p?.name)issues.push({id:uid('AI'),severity:'high',type:'product',message:'Product has no name.',fix:'Set a safe fallback name from SKU or ID.'});if(Number(p?.price)<0)issues.push({id:uid('AI'),severity:'high',type:'product',message:`${p.name||p.id} has a negative price.`,fix:'Set price to zero until reviewed.'});if(Number(p?.stock)<0)issues.push({id:uid('AI'),severity:'medium',type:'inventory',message:`${p.name||p.id} has negative stock.`,fix:'Normalize stock to zero.'});});orders.forEach(o=>{if(!o?.id||!o?.invoice)issues.push({id:uid('AI'),severity:'high',type:'order',message:'Order is missing identity fields.',fix:'Generate missing local identifiers.'});if(Number(o?.total)<0)issues.push({id:uid('AI'),severity:'high',type:'order',message:`${o.invoice||o.id} has a negative total.`,fix:'Recalculate total from line items.'});});customers.forEach(c=>{if(Number(c?.balance)<0)issues.push({id:uid('AI'),severity:'medium',type:'customer',message:`${c.name||c.id} has a negative balance.`,fix:'Flag for review; do not silently alter customer debt.'});});return issues};
export const aiRepair=s=>{const next={...s,products:(s.products||[]).map(p=>({...p,price:Number(p.price)<0?0:p.price,stock:Number(p.stock)<0?0:p.stock,name:p.name||p.sku||p.id})),heldOrders:(s.heldOrders||[]).map(o=>({...o,id:o.id||uid('ORD'),invoice:o.invoice||`FP-${String(Date.now()).slice(-6)}`})),audit:[...(s.audit||[]),{id:uid('AUD'),date:today(),action:'Offline AI repaired safe data integrity issues',by:'AI'}]};return next};
export const aiCommand=(input,s,user)=>{const q=String(input||'').trim().toLowerCase();if(!q)return{ok:false,reply:'Tell me what you want me to do.'};if(/fix|repair|heal|integrity/.test(q)){if(!aiRoleCan(user?.role,'repair'))return{ok:false,reply:'I found the repair command, but Admin or Owner approval is required.'};const issues=aiDiagnostics(s);return{ok:true,action:'repair',state:aiRepair(s),reply:issues.length?`I repaired ${issues.length} safe data issue(s) and logged the changes.`:'Health check is clean. No repair was required.',issues};}if(/health|diagnos|check.*issue|problem/.test(q)){const issues=aiDiagnostics(s);return{ok:true,action:'diagnose',reply:issues.length?`${issues.length} issue(s) need attention.`:'Everything looks healthy.',issues};}if(/inventory|stock/.test(q)){const low=(s.products||[]).filter(p=>Number(p.stock)<=5);return{ok:true,action:'read',reply:low.length?`${low.length} products are at or below 5 units: ${low.map(p=>p.name).join(', ')}.`:'Inventory is healthy; no product is at or below 5 units.',data:{lowStock:low}};}if(/sales|revenue|today/.test(q)){const total=(s.sales||[]).reduce((a,x)=>a+Number(x.total||0),0);return{ok:true,action:'read',reply:`Recorded sales total is ${money(total)}.`,data:{salesTotal:total}};}return{ok:true,action:'suggest',reply:'I can diagnose and safely repair data, monitor inventory, summarize sales, inspect orders, and guide counter operations offline.'};};
