const KEY='findupto-pos-v3';
const api=()=>window.mkPosDesktop?.project||null;
const load=()=>{try{const d=window.mkPosDesktop?.database;return d?.loadState?.()||JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const save=s=>{try{const d=window.mkPosDesktop?.database;if(d?.saveState)d.saveState(s,'project-ai');else localStorage.setItem(KEY,JSON.stringify(s));}catch{}};
const admin=()=>/admin|owner/i.test(document.querySelector('.user-chip small')?.textContent||'');
const esc=v=>String(v??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const audit=(s,a)=>{s.audit=[...(s.audit||[]),{id:`AI-${Date.now()}`,date:new Date().toLocaleString(),action:a,by:'project-ai'}]};
function runtime(css){let x=document.getElementById('project-ai-runtime');if(!x){x=document.createElement('style');x.id='project-ai-runtime';document.head.appendChild(x)}x.textContent+=`\n/* Project AI runtime change */\n${css}`;return true}
function colorName(v){const m={orange:'#f97316',blue:'#2563eb',red:'#dc2626',green:'#16a34a',purple:'#7c3aed',violet:'#7c5cff',pink:'#db2777',black:'#111827',white:'#ffffff',gray:'#6b7280',grey:'#6b7280',teal:'#0d9488',cyan:'#0891b2',yellow:'#eab308'};return m[v.toLowerCase()]||v}
function cssCommand(q){let t=q.trim(),x;
 if((x=t.match(/(?:change|set|make)\s+(?:the\s+)?(?:primary|accent)\s+colou?r\s+(?:to\s+)?(.+)/i)))return{css:`:root{--accent:${colorName(x[1].trim())}!important}.primary,.sidebar nav button.active{background:${colorName(x[1].trim())}!important}`,text:`Primary/accent color changed to ${x[1].trim()}.`};
 if((x=t.match(/(?:change|set|make)\s+(?:the\s+)?background\s+(?:to\s+)?(.+)/i)))return{css:`body{background:${colorName(x[1].trim())}!important}`,text:`Application background changed to ${x[1].trim()}.`};
 if((x=t.match(/(?:change|set|make)\s+(?:the\s+)?(?:sidebar|side bar)\s+(?:width|size)\s+(?:to|=)\s*(\d+)\s*(px|rem|%)?/i)))return{css:`.sidebar{width:${x[1]}${x[2]||'px'}!important;flex-basis:${x[1]}${x[2]||'px'}!important}.main{width:calc(100% - ${x[1]}${x[2]||'px'})!important}`,text:`Sidebar width changed to ${x[1]}${x[2]||'px'}.`};
 if((x=t.match(/(?:make|set|change)\s+(?:all\s+)?(?:buttons|button)\s+(?:radius|rounded)\s+(?:to|=)\s*(\d+)\s*(px)?/i)))return{css:`button{border-radius:${x[1]}${x[2]||'px'}!important}`,text:`Button radius changed to ${x[1]}${x[2]||'px'}.`};
 if((x=t.match(/(?:change|set|make)\s+(?:the\s+)?font(?:\s+family)?\s+(?:to|=)\s+(.+)/i)))return{css:`body,button,input,select{font-family:${x[1].trim()},Inter,system-ui,sans-serif!important}`,text:`Font changed to ${x[1].trim()}.`};
 if((x=t.match(/(?:set|change)\s+([.#][\w-]+)\s+([\w-]+)\s+(?:to|=)\s+(.+)/i)))return{css:`${x[1]}{${x[2]}:${x[3].trim()}!important}`,text:`Changed ${x[1]} ${x[2]} to ${x[3].trim()}.`};
 if((x=t.match(/(?:hide|remove)\s+(?:the\s+)?([.#][\w-]+)/i)))return{css:`${x[1]}{display:none!important}`,text:`${x[1]} is now hidden.`};
 if((x=t.match(/(?:show|restore)\s+(?:the\s+)?([.#][\w-]+)/i)))return{css:`${x[1]}{display:revert!important}`,text:`${x[1]} is visible again.`};
 if(/dark mode|make .*dark|dark theme/i.test(t))return{css:`body{background:#0b1220!important;color:#e5e7eb!important}.panel,.stat,.product-card,.cart,.main>header{background:#111827!important;color:#e5e7eb!important}.sidebar{background:#070d18!important}`,text:'Dark visual mode applied.'};
 if(/light mode|make .*light|light theme/i.test(t))return{css:`body{background:#f5f6f8!important;color:#18202a!important}.panel,.stat,.product-card,.cart,.main>header{background:#fff!important;color:#18202a!important}.sidebar{background:#111827!important}`,text:'Light visual mode applied.'};
 return null}
async function projectFiles(){return api()?.list?api().list():[]}
async function readFile(path){return api()?.read?api().read(path):{ok:false,error:'Project file access unavailable'}}
async function writeFile(path,content){return api()?.write?api().write(path,content):{ok:false,error:'Project file access unavailable'}}
async function sourceEdit(q){if(!api()?.write)return null;let m=q.match(/(?:edit|modify|update|change)\s+(?:file\s+)?([\w./-]+)\s+(?:replace|change)\s+["']([\s\S]*?)["']\s+(?:with|to)\s+["']([\s\S]*?)["']\s*$/i);if(!m)return null;const r=await readFile(m[1]);if(!r?.ok)return{ok:false,text:`I could not read ${m[1]}.`};if(!r.content.includes(m[2]))return{ok:false,text:`I could not find the requested text in ${m[1]}.`};const next=r.content.replace(m[2],m[3]);const w=await writeFile(m[1],next);return{ok:!!w?.ok,text:w?.ok?`Updated ${m[1]} and created a backup first.`:`I could not update ${m[1]}: ${w?.error||'unknown error'}.`}}
async function answer(q){const t=String(q||'').trim();if(!t)return null;if(!admin())return{state:load(),text:'Project-level AI changes are restricted to Admin/Owner. I can still provide read-only assistance to other staff.'};const c=cssCommand(t);if(c){runtime(c.css);const s=load();audit(s,`Project AI style change: ${c.text}`);save(s);return{state:s,text:`✓ ${c.text} The change is applied immediately.`}}const e=await sourceEdit(t);if(e)return{state:load(),text:e.text};if(/list project files|show project files|what files/i.test(t)){const f=await projectFiles();return{state:load(),text:f?.length?`Project files: ${f.join(', ')}`:'Project file listing is unavailable.'}}if(/read file\s+/i.test(t)){const p=t.replace(/^.*read file\s+/i,'').trim();const r=await readFile(p);return{state:load(),text:r?.ok?`FILE ${p}\n${r.content.slice(0,8000)}`:`Could not read ${p}.`}}return{state:load(),text:'I can directly control the running UI and, as Admin/Owner, safely edit project source files with automatic backups. Try: “change primary color to blue”, “make sidebar width 300px”, “make buttons rounded 18px”, “dark mode”, “hide .date”, or “edit file src/styles.css replace "..." with "..."”.'}}
window.finduptoProjectAI={answer,runtime};

function isProjectCommand(q){return /\b(change|set|make|hide|remove|show|restore|edit|modify|update|dark mode|light mode|theme|font|sidebar|background|primary|accent|button|file)\b/i.test(String(q||'')) && (/style|color|colour|background|sidebar|button|font|theme|mode|file|css|layout|width|height|radius|hide|show|remove/i.test(String(q||'')));}
function postResult(text){const body=document.querySelector('#oai-body');if(!body)return;const d=document.createElement('div');d.className='oai-msg';d.innerHTML=esc(text).replace(/\n/g,'<br>');body.appendChild(d);body.scrollTop=body.scrollHeight;}
async function intercept(){if(window.__finduptoProjectAiHook)return;window.__finduptoProjectAiHook=true;document.addEventListener('keydown',async e=>{if(e.key!=='Enter'||e.shiftKey)return;const el=e.target;if(!el.matches?.('.oai-compose input'))return;const q=el.value.trim();if(!isProjectCommand(q))return;e.preventDefault();e.stopImmediatePropagation();const r=await answer(q);postResult(r?.text||'Project AI could not complete that change.');el.value='';},true);document.addEventListener('click',async e=>{const b=e.target.closest?.('.oai-compose button');if(!b)return;const el=document.querySelector('.oai-compose input');const q=el?.value?.trim()||'';if(!isProjectCommand(q))return;e.preventDefault();e.stopImmediatePropagation();const r=await answer(q);postResult(r?.text||'Project AI could not complete that change.');if(el)el.value='';},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',intercept);else intercept();
