import {uid} from './posData';

export const PROMOTION_TYPES=['PERCENT','FIXED','BOGO','COMBO','HAPPY_HOUR','COUPON'];
export const createPromotion=(data={})=>({id:uid('PROMO'),name:data.name||'New Promotion',code:data.code||'',type:data.type||'PERCENT',value:Number(data.value)||0,productIds:data.productIds||[],categoryIds:data.categoryIds||[],customerSegments:data.customerSegments||[],days:data.days||[],startTime:data.startTime||null,endTime:data.endTime||null,minSubtotal:Number(data.minSubtotal)||0,maxDiscount:Number(data.maxDiscount)||null,usageLimit:data.usageLimit==null?null:Number(data.usageLimit),usageCount:0,stackable:data.stackable===true,active:data.active!==false,startsAt:data.startsAt||null,endsAt:data.endsAt||null,createdAt:new Date().toISOString()});
export const promotionEligible=(promo,{subtotal=0,productId=null,categoryId=null,segment=null,date=new Date(),used=0}={})=>{if(!promo?.active||Number(subtotal)<Number(promo.minSubtotal||0))return false;if(promo.startsAt&&date<new Date(promo.startsAt))return false;if(promo.endsAt&&date>new Date(promo.endsAt))return false;if(promo.usageLimit!=null&&Number(used)>=Number(promo.usageLimit))return false;if(promo.productIds?.length&&!promo.productIds.includes(productId))return false;if(promo.categoryIds?.length&&!promo.categoryIds.includes(categoryId))return false;if(promo.customerSegments?.length&&!promo.customerSegments.includes(segment))return false;if(promo.days?.length&&!promo.days.includes(date.getDay()))return false;const mins=date.getHours()*60+date.getMinutes(),parse=s=>s?Number(s.split(':')[0])*60+Number(s.split(':')[1]):null;const a=parse(promo.startTime),b=parse(promo.endTime);return!(a!=null&&b!=null&&(mins<a||mins>b))};
export const discountFor=(promo,subtotal,eligibleSubtotal=subtotal)=>{if(!promo)return 0;let d=promo.type==='PERCENT'?eligibleSubtotal*Number(promo.value||0)/100:promo.type==='FIXED'||promo.type==='COUPON'?Number(promo.value||0):promo.type==='BOGO'?Math.floor(Math.max(0,eligibleSubtotal)/Math.max(0.01,Number(promo.buyPrice||1)))*Number(promo.freePrice||0):promo.type==='COMBO'?Number(promo.value||0):0;return Math.min(Math.max(0,d),Number(promo.maxDiscount||Infinity),Number(subtotal||0))};
export const applyPromotions=(cart,promotions=[],context={})=>{let subtotal=(cart||[]).reduce((s,i)=>s+Number(i.price||0)*Number(i.qty||0),0),discount=0,applied=[];for(const p of promotions){if(!promotionEligible(p,{...context,subtotal,date:context.date||new Date()}))continue;if(!p.stackable&&applied.length)continue;const d=discountFor(p,subtotal,subtotal-discount);if(d>0){discount+=d;applied.push({promotionId:p.id,name:p.name,discount:d});}}return{subtotal,discount,total:Math.max(0,subtotal-discount),applied}};
export const couponLookup=(promotions,code)=>(promotions||[]).find(p=>p.active!==false&&String(p.code||'').toLowerCase()===String(code||'').trim().toLowerCase());
export const incrementUsage=promo=>({...promo,usageCount:Number(promo.usageCount||0)+1});
export const promotionUsage=(promotions=[])=>promotions.map(p=>({id:p.id,name:p.name,used:Number(p.usageCount||0),limit:p.usageLimit,remaining:p.usageLimit==null?null:Math.max(0,Number(p.usageLimit)-Number(p.usageCount||0))}));
