import {uid} from './posData';

export const PROMO_TYPES=['PERCENT','FIXED','BUY_X_GET_Y','COMBO','HAPPY_HOUR','COUPON','CUSTOMER_PRICE'];
export const createPromotion=(data={})=>({id:uid('PROMO'),name:data.name||'New Promotion',type:data.type||'PERCENT',active:data.active!==false,priority:Number(data.priority)||0,startAt:data.startAt||null,endAt:data.endAt||null,days:data.days||[0,1,2,3,4,5,6],locationIds:data.locationIds||['*'],productIds:data.productIds||[],categoryIds:data.categoryIds||[],customerIds:data.customerIds||[],percent:Number(data.percent)||0,amount:Number(data.amount)||0,minSpend:Number(data.minSpend)||0,coupon:String(data.coupon||'').trim().toUpperCase(),stackable:data.stackable===true,conditions:data.conditions||{}});
export const promotionEligible=(p,{now=new Date(),locationId='MAIN',customerId=null,productId=null,categoryId=null,subtotal=0,coupon='' }={})=>{if(!p?.active)return false;const t=new Date(now),day=t.getDay();if(p.startAt&&t<new Date(p.startAt))return false;if(p.endAt&&t>new Date(p.endAt))return false;if(!(p.days||[]).includes(day))return false;if(!((p.locationIds||['*']).includes('*')||(p.locationIds||[]).includes(locationId)))return false;if(p.minSpend&&Number(subtotal)<Number(p.minSpend))return false;if(p.customerIds?.length&&!p.customerIds.includes(customerId))return false;if(p.productIds?.length&&!p.productIds.includes(productId))return false;if(p.categoryIds?.length&&!p.categoryIds.includes(categoryId))return false;if(p.coupon&&p.coupon!==String(coupon||'').trim().toUpperCase())return false;return true};
export const discountForPromotion=(p,subtotal,qty=1)=>{const base=Math.max(0,Number(subtotal)||0);if(p.type==='PERCENT'||p.type==='HAPPY_HOUR'||p.type==='COUPON')return Math.min(base,base*(Number(p.percent)||0)/100);if(p.type==='FIXED')return Math.min(base,Number(p.amount)||0);if(p.type==='BUY_X_GET_Y'){const buy=Math.max(1,Number(p.conditions?.buy)||1),get=Math.max(1,Number(p.conditions?.get)||1);return qty>=buy+get?Math.min(base,(Number(p.amount)||0)*get):0}return 0};
export const bestPromotions=(promotions,context)=> (promotions||[]).filter(p=>promotionEligible(p,context)).sort((a,b)=>Number(b.priority)-Number(a.priority));
export const applyPromotions=(promotions,context={})=>{const eligible=bestPromotions(promotions,context);let total=Number(context.subtotal)||0,applied=[];for(const p of eligible){if(applied.length&&!p.stackable)continue;const d=Math.min(total,discountForPromotion(p,total,context.qty));if(d>0){applied.push({promotionId:p.id,name:p.name,type:p.type,discount:d});total-=d}}return{discount:(Number(context.subtotal)||0)-total,total,applied};};
export const customerPrice=(prices,{productId,customerId,locationId='MAIN'}={})=>(prices||[]).find(p=>p.productId===productId&&p.customerId===customerId&&(!p.locationId||p.locationId===locationId)&&p.active!==false)?.price??null;
export const comboTotal=(items,components)=> (components||[]).reduce((sum,c)=>sum+Number(c.price||items.find(i=>i.productId===c.productId)?.price||0)*Number(c.qty||1),0);
