import {uid} from './posData';

export const RECEIPT_FORMATS=['THERMAL_58','THERMAL_80','A4'];
export const createReceiptTemplate=({name='Default Receipt',format='THERMAL_80',header={},footer={},showLogo=true,showTax=true,showDiscount=true,showPayment=true,showQr=true}={})=>({id:uid('TPL'),name,format,header,footer,showLogo,showTax,showDiscount,showPayment,showQr,active:true});
export const receiptData=(order,{business={},template=null,refund=false}={})=>({id:uid('RCP'),orderId:order?.id,orderNo:order?.orderNo||'',date:order?.createdAt||new Date().toISOString(),business,template,customer:order?.customer||{name:order?.customerName||'',phone:order?.phone||''},table:order?.tableName||order?.table||'',items:(order?.items||[]).map(i=>({name:i.name||i.productName,qty:Number(i.qty||0),price:Number(i.price||0),total:Number(i.qty||0)*Number(i.price||0)})),subtotal:Number(order?.subtotal||0),discount:Number(order?.discount||0),tax:Number(order?.tax||0),total:Number(order?.total||0),payments:order?.payments||[],refund});
export const thermalReceiptText=(data,{width=80}={})=>{const line='-'.repeat(width);const center=s=>String(s||'').padStart(Math.floor((width+String(s||'').length)/2));const rows=[center(data.business?.name||''),data.business?.address||'',data.business?.phone||'',line,`Order: ${data.orderNo}`,`Date: ${data.date}`,data.customer?.name?`Customer: ${data.customer.name}`:'',line,...data.items.map(i=>`${i.qty} x ${i.name} ${i.total.toFixed(2)}`),line,`Subtotal: ${data.subtotal.toFixed(2)}`,data.discount?`Discount: -${data.discount.toFixed(2)}`:'',data.tax?`Tax: ${data.tax.toFixed(2)}`:'',`TOTAL: ${data.total.toFixed(2)}`,...(data.payments||[]).map(p=>`${p.method}: ${Number(p.amount||0).toFixed(2)}`),line,data.refund?'*** REFUND ***':'',data.template?.footer?.text||'Thank you!'];return rows.filter(Boolean).join('\n')};
export const invoiceTotals=(order)=>({subtotal:Number(order?.subtotal||0),discount:Number(order?.discount||0),tax:Number(order?.tax||0),total:Number(order?.total||0),paid:(order?.payments||[]).reduce((s,p)=>s+Number(p.amount||0),0),balance:Math.max(0,Number(order?.total||0)-(order?.payments||[]).reduce((s,p)=>s+Number(p.amount||0),0))});
export const createQrPayload=(order)=>JSON.stringify({orderId:order?.id,orderNo:order?.orderNo,total:Number(order?.total||0)});
export const barcodePayload=(value,type='CODE128')=>({type,value:String(value||'')});
export const kitchenPrintData=ticket=>({ticketId:ticket?.id,orderNo:ticket?.orderNo,tableName:ticket?.tableName,priority:ticket?.priority,createdAt:ticket?.createdAt,items:(ticket?.items||[]).map(i=>({name:i.name,qty:i.qty,station:i.station,notes:i.notes,state:i.state}))});
export const customerDisplayData=sale=>({orderNo:sale?.orderNo||'',items:(sale?.items||[]).map(i=>({name:i.name,qty:i.qty,price:i.price,total:Number(i.qty||0)*Number(i.price||0)})),subtotal:Number(sale?.subtotal||0),discount:Number(sale?.discount||0),tax:Number(sale?.tax||0),total:Number(sale?.total||0)});
export const refundReceiptData=(order,refund)=>receiptData({...order,refunds:[refund],total:Number(refund?.amount||0),payments:[{method:refund?.method||'REFUND',amount:Number(refund?.amount||0)}]},{refund:true});
