import {today} from './posData';

const sum=(rows,key)=>rows.reduce((s,r)=>s+Number(r?.[key]||0),0);
export const salesReport=(sales=[],filters={})=>{const rows=sales.filter(s=>(!filters.locationId||s.locationId===filters.locationId)&&(!filters.employeeId||s.employeeId===filters.employeeId)&&(!filters.from||String(s.date||s.createdAt||'')>=filters.from)&&(!filters.to||String(s.date||s.createdAt||'')<=filters.to));return{rows,orders:rows.length,revenue:sum(rows,'total'),tax:sum(rows,'tax'),discount:sum(rows,'discount'),net:sum(rows,'total')-sum(rows,'discount'),averageOrder:rows.length?sum(rows,'total')/rows.length:0}};
export const productSalesReport=(sales=[])=>{const out={};for(const s of sales)for(const i of s.items||[]){const k=i.productId||i.name||'UNKNOWN';out[k]??={productId:i.productId,name:i.name||i.productName,qty:0,revenue:0};out[k].qty+=Number(i.qty||0);out[k].revenue+=Number(i.qty||0)*Number(i.price||0)}return Object.values(out).sort((a,b)=>b.revenue-a.revenue)};
export const categorySalesReport=(sales=[],products=[])=>{const map=new Map((products||[]).map(p=>[p.id,p.categoryId||p.category||'UNCATEGORIZED']));const out={};for(const s of sales)for(const i of s.items||[]){const k=map.get(i.productId)||i.categoryId||'UNCATEGORIZED';out[k]??={categoryId:k,qty:0,revenue:0};out[k].qty+=Number(i.qty||0);out[k].revenue+=Number(i.qty||0)*Number(i.price||0)}return Object.values(out).sort((a,b)=>b.revenue-a.revenue)};
export const paymentReport=(payments=[])=>Object.values(payments.reduce((a,p)=>{const k=p.method||'OTHER';a[k]??={method:k,count:0,amount:0,refunded:0};a[k].count++;a[k].amount+=Number(p.amount||0);a[k].refunded+=Number(p.refundedAmount||0);return a},{}));
export const staffSalesReport=(sales=[])=>Object.values(sales.reduce((a,s)=>{const k=s.employeeId||s.cashierId||'UNKNOWN';a[k]??={employeeId:k,orders:0,revenue:0};a[k].orders++;a[k].revenue+=Number(s.total||0);return a},{})).sort((a,b)=>b.revenue-a.revenue);
export const hourlySalesReport=(sales=[])=>Array.from({length:24},(_,hour)=>{const rows=sales.filter(s=>new Date(s.createdAt||s.date||Date.now()).getHours()===hour);return{hour,orders:rows.length,revenue:sum(rows,'total')}});
export const profitReport=(sales=[],cogsByOrder={})=>{const revenue=sum(sales,'total'),tax=sum(sales,'tax'),discount=sum(sales,'discount'),cogs=sales.reduce((s,o)=>s+Number(cogsByOrder[o.id]||o.cogs||0),0);const netSales=revenue-discount;return{revenue,discount,tax,netSales,cogs,grossProfit:netSales-cogs,margin:netSales?(netSales-cogs)/netSales*100:0}};
export const taxReport=(sales=[])=>Object.values(sales.reduce((a,s)=>{for(const t of s.taxes||[{code:'TOTAL',amount:s.tax||0}]){const k=t.code||'TOTAL';a[k]??={code:k,taxable:0,tax:0};a[k].taxable+=Number(t.taxable||s.subtotal||0);a[k].tax+=Number(t.amount||0)}return a},{}));
export const inventoryReport=(lots=[])=>({items:lots.reduce((s,l)=>s+Number(l.quantity||0),0),value:lots.reduce((s,l)=>s+Number(l.quantity||0)*Number(l.cost||0),0),expiring:lots.filter(l=>l.expiryDate&&new Date(l.expiryDate)>new Date()).length,expired:lots.filter(l=>l.expiryDate&&new Date(l.expiryDate)<new Date()&&Number(l.quantity)>0).length});
export const managementKpis=({sales=[],cogsByOrder={},lots=[],payments=[]}={})=>{const s=salesReport(sales),p=profitReport(sales,cogsByOrder);return{date:today(),revenue:s.revenue,orders:s.orders,averageOrder:s.averageOrder,grossProfit:p.grossProfit,margin:p.margin,inventoryValue:inventoryReport(lots).value,paymentCount:payments.length}};
export const exportRows=(rows=[])=>rows.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k,typeof v==='object'?JSON.stringify(v):v])));
