import React,{useState} from 'react';
import {BookOpen,CheckCircle,ChevronLeft,ChevronRight,Upload,Package,Receipt,Boxes,ShoppingCart,Lightbulb} from 'lucide-react';
import {Panel} from './businessModules';

const LESSONS=[
 {title:'Welcome & setup',icon:BookOpen,body:'Start here if this is your first day using the POS. Complete the lessons in order. The tutorial explains menu setup, ingredients, recipes, deals, purchases, sales and stock checks.',tips:['Open Settings and confirm business name, address, phone and currency.','Create the staff accounts you need and give each person only the access they need.']},
 {title:'Create your menu',icon:Package,body:'Add the items you sell: pizzas, burgers, shawarma, biryani, shakes, cold drinks and other products. A menu item is what the cashier sells at the POS.',tips:['Use a unique SKU for each item.','For size variants, create separate products such as Pizza Small, Pizza Medium, Pizza Large and Pizza XL.','Keep menu selling price and ingredient cost separate.']},
 {title:'Add ingredients & stock',icon:Boxes,body:'Ingredients are your real stock: milk, mango, cream, sugar, cheese, mayonnaise, chicken, rice, oil, spices and so on. Purchase or adjust their quantities using a consistent base unit.',tips:['Prefer g, kg, ml, L and pcs consistently.','For recipe calculations, smaller base units such as grams and millilitres make fractional quantities easier.','Do not treat a finished recipe as raw ingredient stock unless it is intentionally a batch/semi-finished product.']},
 {title:'Build recipes',icon:Receipt,body:'Attach ingredients to a menu item and define how much is consumed for one sale. Example: a Large Mango Shake can use 300 ml milk, 150 g mango, 45 g cream and 35 g sugar.',tips:['Recipe quantity means consumption per one menu unit.','Shared ingredients can belong to many recipes; selling any of those items reduces the same ingredient stock.','Add waste percentage when preparation normally loses some quantity.']},
 {title:'Create & import deals',icon:Upload,body:'Deals are bundles of existing menu items. During CSV import, mark a row as Deal/Bundle or provide deal components. The system attempts to match components by SKU or exact/unique product name and places recognized deals in the Deals tab.',tips:['Example components: Zinger Burger + Fries + Cold Drink.','If a component cannot be matched safely, edit the deal manually instead of guessing.','Bulk import normal menu rows first in the same CSV so deal components can be matched.']},
 {title:'Sell at POS',icon:ShoppingCart,body:'When a cashier completes a sale, the POS records the sale and the inventory engine consumes the recipe ingredients. A deal consumes its component products. A normal stock item without a recipe reduces its own stock.',tips:['Use the exact size/variant sold so the correct recipe is consumed.','The available quantity of a recipe item is limited by its ingredient with the least remaining capacity.','Never manually reduce ingredient stock after a normal sale unless correcting a real inventory discrepancy.']},
 {title:'Check stock & demand',icon:Lightbulb,body:'Use Inventory and sales history to compare what should remain with what is physically present. Repeated sales can also be used to estimate purchasing demand.',tips:['Example: 50 pizzas × average 150 g cheese = about 7.5 kg cheese consumption.','For a 7-day plan, multiply average daily consumption by 7 and subtract usable stock to estimate the purchase requirement.','Investigate large variances as waste, over-portioning, wrong recipes or stock leakage.']},
 {title:'Biryani & batch production',icon:Boxes,body:'For products prepared in batches, record the prepared batch as a stock item when appropriate. Example: produce 50 kg biryani, then sell 250 g, 500 g or 1 kg portions from that batch.',tips:['Keep the raw ingredient recipe for the batch if you want production-level costing.','Track the finished batch separately when the kitchen prepares it before sale.','Use consistent units so 50 kg and 50000 g are never mixed accidentally.']}
];

export default function Tutorial(){const [step,setStep]=useState(0);const lesson=LESSONS[step],Icon=lesson.icon;return <div className="module tutorial"><Panel title="Getting Started Tutorial"><div className="tutorial-progress"><span>Lesson {step+1} of {LESSONS.length}</span><div className="tutorial-bar"><i style={{width:`${((step+1)/LESSONS.length)*100}%`}}/></div></div><div className="tutorial-card"><div className="tutorial-icon"><Icon size={28}/></div><h2>{lesson.title}</h2><p>{lesson.body}</p><h3>What to do</h3><ul>{lesson.tips.map((x,i)=><li key={i}><CheckCircle size={17}/><span>{x}</span></li>)}</ul></div><div className="tutorial-nav"><button disabled={step===0} onClick={()=>setStep(s=>s-1)}><ChevronLeft size={17}/> Previous</button><div className="tutorial-dots">{LESSONS.map((_,i)=><button aria-label={`Lesson ${i+1}`} className={i===step?'active':''} onClick={()=>setStep(i)} key={i}/>)}</div><button className="primary" disabled={step===LESSONS.length-1} onClick={()=>setStep(s=>s+1)}>Next <ChevronRight size={17}/></button></div></Panel><Panel title="Quick reference"><div className="tutorial-flow"><b>Ingredients</b><span>→</span><b>Recipes</b><span>→</span><b>Menu / Deals</b><span>→</span><b>POS Sale</b><span>→</span><b>Ingredient consumption</b><span>→</span><b>Remaining stock</b></div></Panel></div>}
