import {uid,today} from './posData';

export const SHIFT_STATES=['SCHEDULED','OPEN','ON_BREAK','CLOSED','MISSED'];
export const createEmployee=({name,username='',role='CASHIER',locationIds=['MAIN'],hourlyRate=0,commissionRate=0}={})=>({id:uid('EMP'),name:name||'Employee',username,role,locationIds,hourlyRate:Number(hourlyRate)||0,commissionRate:Number(commissionRate)||0,status:'ACTIVE',createdAt:new Date().toISOString()});
export const createShift=(data={})=>({id:uid('SHF'),employeeId:data.employeeId,locationId:data.locationId||'MAIN',date:data.date||today(),scheduledStart:data.scheduledStart||null,scheduledEnd:data.scheduledEnd||null,startAt:null,endAt:null,status:'SCHEDULED',breaks:[],notes:data.notes||''});
export const clockIn=(shift,user)=>({...shift,startAt:new Date().toISOString(),status:'OPEN',clockedInBy:user?.username||'system'});
export const startBreak=(shift,reason='Break')=>({...shift,status:'ON_BREAK',breaks:[...(shift.breaks||[]),{id:uid('BRK'),startAt:new Date().toISOString(),endAt:null,reason}]});
export const endBreak=shift=>({...shift,status:'OPEN',breaks:(shift.breaks||[]).map((b,i,a)=>i===a.length-1&&!b.endAt?{...b,endAt:new Date().toISOString()}:b)});
export const clockOut=(shift,user)=>({...shift,endAt:new Date().toISOString(),status:'CLOSED',clockedOutBy:user?.username||'system'});
export const workedMinutes=(shift,now=new Date())=>{if(!shift?.startAt)return 0;const end=shift.endAt?new Date(shift.endAt):now;let mins=Math.max(0,Math.floor((end-new Date(shift.startAt))/60000));for(const b of shift.breaks||[])if(b.startAt)mins-=Math.max(0,Math.floor(((b.endAt?new Date(b.endAt):now)-new Date(b.startAt))/60000));return Math.max(0,mins)};
export const overtimeMinutes=(shift,standardMinutes=480)=>Math.max(0,workedMinutes(shift)-Number(standardMinutes||480));
export const tipAllocation=(employees=[],tips=0)=>{const active=employees.filter(e=>e.status!=='INACTIVE');const each=active.length?Number(tips||0)/active.length:0;return active.map(e=>({employeeId:e.id,tip:Number(each.toFixed(2))}))};
export const employeeCommission=(employee,sales=[])=>sales.filter(s=>s.employeeId===employee?.id).reduce((sum,s)=>sum+Number(s.total||0)*Number(employee?.commissionRate||0)/100,0);
export const payrollSummary=(employees=[],shifts=[],sales=[],tipsByEmployee={})=>employees.map(e=>{const es=shifts.filter(s=>s.employeeId===e.id),minutes=es.reduce((s,x)=>s+workedMinutes(x),0),hours=minutes/60,regular=Math.min(hours,40),overtime=Math.max(0,hours-40),commission=employeeCommission(e,sales);return{employeeId:e.id,name:e.name,regularHours:regular,overtimeHours:overtime,basePay:regular*Number(e.hourlyRate||0),overtimePay:overtime*Number(e.hourlyRate||0)*1.5,commission,tips:Number(tipsByEmployee[e.id]||0),grossEstimate:regular*Number(e.hourlyRate||0)+overtime*Number(e.hourlyRate||0)*1.5+commission+Number(tipsByEmployee[e.id]||0)}});
export const laborAnalytics=(employees=[],shifts=[],sales=[])=>{const minutes=shifts.reduce((s,x)=>s+workedMinutes(x),0),revenue=sales.reduce((s,x)=>s+Number(x.total||0),0);return{employees:employees.length,scheduled:shifts.length,workedHours:minutes/60,laborCost:payrollSummary(employees,shifts,sales).reduce((s,x)=>s+x.grossEstimate,0),salesPerLaborHour:minutes?revenue/(minutes/60):0}};
export const attendanceSummary=(shifts=[],date=today())=>{const rows=shifts.filter(s=>s.date===date);return{date,scheduled:rows.length,open:rows.filter(s=>s.status==='OPEN'||s.status==='ON_BREAK').length,closed:rows.filter(s=>s.status==='CLOSED').length,missed:rows.filter(s=>s.status==='MISSED').length,totalMinutes:rows.reduce((s,x)=>s+workedMinutes(x),0)}};
